### ISSUE TITLE
Great achievement

### ISSUE THREAD

**Issue by goldenwebsites** [ratson/cordova-plugin-admob-free#1]
Not really an issue, but just wondering, how did you manage to achieve such a stable download chart on npm

http://npm-stat.com/charts.html?package=cordova-plugin-admob-free&author=&from=2015-05-21&to=2016-05-20

It's quite rare actually and quite unheard of. Check native storage for example.

http://npm-stat.com/charts.html?package=cordova-plugin-nativestorage&author=&from=2015-05-21&to=2016-05-20

I'm a bit of a statistics nut so just curious. The npm stats system is notorious for being difficult to understand, jumping around a lot and not really representing real actual downloads by people.

Is the plugin listed somewhere else besides the cordova plugins page?

**Comment by ratson** [comment]
Thanks for the information, no idea how `npm` counts downloads.
Let me know if you find out the answer.

Did not submit to any list, but not sure if mentioned in any list.
