### ISSUE TITLE
Always displaying default ads

### ISSUE THREAD

**Issue by erperejildo** [ratson/cordova-plugin-admob-free#103]
Maybe I'm doing something wrong because I can't get rid of the default ads.
This is my config:
```
let admobId = {};
            if( /(android)/i.test(navigator.userAgent) ) {
                admobId = {
                    banner: 'MY-ID',
                    interstitial: 'MY-ID',
                    video: 'MY-ID'
                };
            }

            admob.banner.config({
                id: admobId.banner
            });

            admob.interstitial.config({
                id: admobId.interstitial
            });
```
And to display it `admob.interstitial.prepare();`

**Comment by erperejildo** [comment]
to test it has to be on production here:
https://play.google.com/store/apps/details?id=com.drodriguez.recipic&hl=en_GB
(just add a Youtube video as a recipe)

**Comment by qpbp** [comment]
Hi, there! I have the similar an issue in my IOS app.

**Comment by ratson** [comment]
@erperejildo Did you solve this?

**Comment by ratson** [comment]
Duplicate to https://github.com/ratson/cordova-plugin-admob-free/issues/69

**Comment by erperejildo** [comment]
Can't test it. Blocked now with https://github.com/ratson/cordova-plugin-admob-free/issues/119
