### ISSUE TITLE
Admob account UI is different now, documentation includes incorrect steps.

### ISSUE THREAD

**Issue by iPzard** [ratson/cordova-plugin-admob-free#108]
This is the phrase I'm talking about:
Go to AdMob portal, click "Monetize a new app" button to create new ad unit.

Current steps:
Apps > Add App. Once App has been added, click the app on the left-hand side and select "Ad units" followed by "ADD AD UNIT"

IMO, to avoid further depreciation I recommend the following wording:
Go to the AdMob portal and add your app (if you haven't done so already), once your app is added to your AdMob account, create a new ad unit for it.

**Comment by ratson** [comment]
Good suggestion, updated accordingly.
