### ISSUE TITLE
How to handles  interstitial dismiss event on ionic 3?

### ISSUE THREAD

**Issue by RafilAlArs** [ratson/cordova-plugin-admob-free#110]

**Comment by tsiliakoudis1** [comment]
for ex. If you want to check when an interstitial is closed you can use:

```
document.addEventListener('admob.interstitial.events.CLOSE', (event) => {
     // do something
     });
```

**Comment by felix9607** [comment]
[https://ratson.github.io/cordova-plugin-admob-free/variable/index.html#static-variable-rewardvideo](url)
here are all admob free events!

btw, dont have to enter sth at 'event', just call any functions below... :)
