### ISSUE TITLE
Phonegap: cannot import the plugin

### ISSUE THREAD

**Issue by msolovyov** [ratson/cordova-plugin-admob-free#116]
Can't seem to get this plugin to work by following the instructions. 
Did phonegap plugin add cordova-plugin-admob-free
Tried: import {banner} from 'cordova-plugin-admob-free/admob'
But it complained it could not find the module. 
Tried: import {banner} from 'cordova-plugin-admob-free/www/admob'
Then got the following error: Cannot find module 'cordova/exec' from 'cordova-plugin-admob-free/www/admob.js'

**Comment by AlfredGjini** [comment]
Hello, I'm having the same problem, were you able to solve it?

**Comment by AlfredGjini** [comment]
You have to wrap it in Ionic Native: npm install --save @ionic-native/admob-free
Check this tutorial: https://ionicframework.com/docs/native/admob-free/

**Comment by ratson** [comment]
@msolovyov Does @AlfredGjini suggestions work for you?
Or you may provide a repo demonstrate your problem, your error seems relate to project setup.

**Comment by msolovyov** [comment]
I'm using plain phonegap and I didn't want to bloat the app by including ionic-native. I ended up using a different admob plugin.

**Comment by ratson** [comment]
Closing this as nothing is actionable.
