### ISSUE TITLE
Not showing ads after update

### ISSUE THREAD

**Issue by erperejildo** [ratson/cordova-plugin-admob-free#119]
Not sure if this is a problem of this library or it's related with Ionic. Either way I created an issue on Ionic repo but I'd like to leave here the link just to double check if someone else is facing the same issue:
https://github.com/ionic-team/ionic-native/issues/2091

Resuming: I can't get this library working with latest version of Ionic (3.7.1). It doesn't display anything and only when I force it to be displayed through the terminal it display a black container.

**Comment by erperejildo** [comment]
No ideas?

**Comment by fobaz** [comment]
Maybe this is related? https://github.com/ratson/cordova-plugin-admob-free/issues/120

**Comment by erperejildo** [comment]
Might be more related with this one: https://github.com/ratson/cordova-plugin-admob-free/issues/118
I don't get any issue here, just no banner at all, but the code seems correct. At least it was working as a charm before updates as I comment

**Comment by bentzibentz** [comment]
Any news on that?

**Comment by 5HARK** [comment]
@erperejildo when i tested it on the pure empty cordova project. it works well.
I proceeded in the following order.
1. Make empty cordova project.
2. Inject cordova-plugin-admob-free example codes ([https://github.com/ratson/cordova-plugin-admob-free/tree/master/examples/basic](url))
3. Test it on Android Emulator.
4. It works well without any problems.(Banner & Interstitial Ads)

**Comment by 5HARK** [comment]
I just tried it again and it works well in my ionic3 + angular4 project.

Below are the tasks I did.

- Update cordova
- Update ionic, ionic-native & etc
- Reinstall cordova-plugin-admob-free

and it works.

**Comment by erperejildo** [comment]
Ok @5HARK I'll try again but as commented this happened to me because I updated everything. I'm using Cordova 7.1.0 which is the latest version: https://www.npmjs.com/package/cordova

I updated, removed node_modules folder, cleaned cache, I ran `cordova prepare` and I tried on Mac and Windows. The only thing I haven't tried is with the emulator.

Tbh I'm almost sure the problem is not this plugin because I also tried the paid one with the same behaviour: doesn't display any banner.

**Comment by erperejildo** [comment]
Ok, just tried with the emulator and works. We are using Ionic and Angular here as well so I don't know what the problem is.

@ratson any ideas?

**Comment by ratson** [comment]
As mentioned in https://github.com/ratson/cordova-plugin-admob-free#ionic-support,
I don't know much about Ionic, which I have no idea what's wrong.

@erperejildo If you prepare a repo with minimum example showing the problem, I would take a look and see if any I could help.

**Comment by erperejildo** [comment]
Sure, I will create a smaller repo with this issue now and the steps to reproduce it

**Comment by erperejildo** [comment]
Ok, I prepared this repo @ratson: https://github.com/erperejildo/admob-free-ionic
One thing, I said that it was working with the emulator and it's not. I tried with the other plugin (the paid one).

**Comment by ratson** [comment]
@erperejildo I updated the dependencies and tested on my Android device, it shows the banner.

![screen](https://user-images.githubusercontent.com/2682937/33084146-293e2fee-cf1c-11e7-93d1-bef1d41e5d2e.png)

Here is my code: https://github.com/ratson/admob-free-ionic

**Comment by erperejildo** [comment]
I tried this:
- Your repo: **worked**
- My app adding this dependencies (Cordova and Ionic): **didn't work**
- I tried my repo (demo) without dependencies: **worked** (unexpected). Before I tried on iOS emulator and didn't work
---------------------
- Copied whole package.json from my app to my repo.
- Removed node_modules folder and ran npm install and removed and added Android platform: **didn't work**

So I understand there are some conflicts with other packages. What I'd do is from my package.json start adding one by one and let's what happens

**Comment by erperejildo** [comment]
I've changed the package.json on the repo as well:
https://github.com/erperejildo/admob-free-ionic/blob/master/package.json

**Comment by erperejildo** [comment]
I'm getting some issue trying on Mac now. Maybe it's not related at all, but just in case. This happens after remove node_modules folder and running `npm install` on the repo with all dependencies (the package from my app):
```
npm ERR! path /Users/danielrodriguez/Desktop/repositories/admob-free-ionic/node_modules/android-versions
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/danielrodriguez/Desktop/repositories/admob-free-ionic/node_modules/android-versions'
npm ERR!  { Error: EACCES: permission denied, access '/Users/danielrodriguez/Desktop/repositories/admob-free-ionic/node_modules/android-versions'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/Users/danielrodriguez/Desktop/repositories/admob-free-ionic/node_modules/android-versions\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/danielrodriguez/Desktop/repositories/admob-free-ionic/node_modules/android-versions' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by ratson** [comment]
@erperejildo Did you find out which plugin causing the issue? I am not going to testing one by one.
I see you have included `cordova-plugin-admobpro`, which likely be the problem as both interact with admob.

**Comment by erperejildo** [comment]
No, I haven't found it yet. I was trying right now in fact. I'm having a lot of permission issues (Mac and Windows) and I don't know why.

Yes, when I couldn't get this working with this one I decided to try that one out to double check it wasn't an Admob issue.

I'll keep you updated

**Comment by erperejildo** [comment]
@ratson this is being quite complex to debug. I'm just removing one by one, removing the whole `node_modules` folder and running `ionic cordova prepare again`.

At some point it worked, it just showed up the banner but when I did exactly the same on my project with that package.json (I was trying on the demo project with the big package.json) it didn't work.

And (which is more weird) when I tried again on the demo project didn't work.

Would be maybe another way to find this issue? What about if I modify something on your plugin that maybe you think it might be a potencial issue or... I don't know, maybe try a different approach. Any sugestiong?

**Comment by trfife** [comment]
I'm having a similar issue. When I hook my phone to logcat I get these errors:

1-30 23:18:14.783 3796-3796/io.ionic.starter W/Ads: Failed to load ad: 2
11-30 23:18:14.783 3796-3796/io.ionic.starter D/CordovaWebViewImpl: >>> loadUrl(javascript:cordova.fireDocumentEvent('admob.banner.events.LOAD_FAIL',{"error":2,"reason":"Network Error","adType":"banner"});)
11-30 23:18:14.784 3796-3796/io.ionic.starter D/CordovaWebViewImpl: >>> loadUrl(javascript:cordova.fireDocumentEvent('onFailedToReceiveAd',{"error":2,"reason":"Network Error","adType":"banner"});)

I'm going to try an empty app and see if it's not working.

**Comment by erperejildo** [comment]
Might be a different one maybe because I don't get any errors at all, but try that, a new project and use on that project your package.json from the real project

**Comment by cesarmart76** [comment]
Recently I had a similar issue. The problem was that my app was in the Designed for Families program of Google (in the Google Play Console settings).

Removing my app from this program solved the issue. Apparently ads not show when you are in this program.

**Comment by erperejildo** [comment]
Well, mine is in Designed for Families program as well, but tbh that's not related with local deployment. And also doesn't make any sense because you still having the option on your developer console to check if you app is displaying ads or not.

> If you have opted your app(s) in to Google Play's Designed for Families program and you show ads in your app(s), you need to ensure those ads comply with the Designed for Families program requirements and ad policies. AdMob offers the following tools for publishers to show ads that are compliant with the Designed for Families program policies.

More info: https://support.google.com/admob/answer/6223431?hl=en

**Comment by erperejildo** [comment]
This is another app that I've got (an old one):
https://play.google.com/store/apps/details?id=drodriguez.apps.Words

It's using this plugin as well and it's also in Designed for Families program. Doesn't have any problem with any kid of banners

**Comment by erperejildo** [comment]
@trfife did you find something btw?

**Comment by trfife** [comment]
@erperejildo After fighting with it for a while I decided to give up on ads and do an in-app-purchase instead to generate revenue since I needed to complete this project by last Sunday. Luckily, with this app I could just turn off a feature till the user makes the purchase. As for the conversation above, I hadn't even got to the play store yet when I hit this error so I hadn't set if my app was for families or not. I was still just testing directly on my device so I don't think that played any part. From looking at the logs it looks like something with the connection is messed up, I was seeing that network error above. I couldn't get the test ads or real ads to show up. I am very interested in a solution though because I have another app in the works that I'd like to put ads on.

**Comment by cesarmart76** [comment]
If you are having trouble with this, I recommend to change the package name of your app just for testing (Ex. com.testing54.asdadas). I spend hours and hours trying to fix this problem with the ads and at the end it was nothing related with the plugin or with Ionic/Cordova, the problem was with Google.

If you are using a package name who already exists, and that package name is related to an app who is in the Design For Families program of Google, or is banned from AdMob, you will not see the ads. Even if you are only debugging (trust me, I was only debugging and using test ads and this solved the issue).

Maybe this is not your issue, but you will only spend 5 minutes trying.

Good luck.

**Comment by erperejildo** [comment]
@trfife I really sorry to hear that. Definitely this needs to be fixed ASAP. We're not talking here about a specific feature, is the main thing: we can't display any ads at all. Did you try at least with the pro one?
I'm almost sure that the problem is not related with this plugin anyway. And not even with Ionic. But tbh after all of this time I have no idea...

@cesarmart76 that's interesting. As commented right now I also think that the problem could come from Google. In fact I was doing exactly that: use an existing package name from an app already published and designed for families.

I have no cable to try it right now but if it works... what would happen if I need to use that package name? I want to update my old app which is using Angular 1.2 to the one I've got right now with Ionic and Angular 5.

**Comment by erperejildo** [comment]
Ok, I ran `npm update` and tried again and everything is working again!!

**Comment by erperejildo** [comment]
...bad failing again   :(

**Comment by erperejildo** [comment]
App updated on Google Play and ads not working

**Comment by erperejildo** [comment]
I've been doing some workaround (again) with this.
- Installed Pro version: working
- After some changes: not working
- Removing Pro version and installing this one again: working (?)
- After some changes: not working

With "some changes" I just mean creating variables or something really stupid. It just makes no %$£%$% sense to me.

**Comment by erperejildo** [comment]
Found this link:
https://support.google.com/admob/answer/7562314?ctx=email

> Starting January 23, 2018, we will no longer support Google Mobile Ads (GMA) SDK versions lower than 7.0.0 for Android or iOS. To continue serving mobile ads from AdMob, Ad Exchange, or DFP after this date, please upgrade to the latest Google Mobile Ads SDK

**Comment by uncrabe** [comment]
Same issue here, but only with interstitials...

**Comment by erperejildo** [comment]
@uncrabe you should have problem with both.

...the more time I spend looking into this the further away I feel to get a solution  :S

**Comment by Om3s** [comment]
I have the same issue, I'm using ionic firebase and ionic native admob-free. Am not able to show interstitials only if I set isTesting = true.
The interstitial never gets ready, so it never shows up.

@erperejildo Have you found a solution yet?

**Comment by erperejildo** [comment]
@Om3s my solution was install admob-pro.

When I tried it before it wasn't working either but only because (I don't know why) I need to install some specific plugins manually (like that one or the status bar). So give it a try

**Comment by erperejildo** [comment]
I load my banner at beginning so I didn't face that (and if I do don't care too much as long it's the main page with the logo)

**Comment by aabdolla** [comment]
@erperejildo Oh okay. How does it work on iPhone X? That is the only reason I would switch right now as I can't get the banner on the bottom to be above the round corners/safe area.

**Comment by ChadKoder** [comment]
I only see ads display once on a fresh install of the app, then never again until I delete the app and re-install it.  It will then show once, then never again.. Come on someone, fix this! :)

**Comment by erperejildo** [comment]
@aabdolla I don't know, I haven't tried on that one but you must have to ask these questions on that repo.

Yes @ChadKoder I see similar issue. PRs are welcomed btw.

**Comment by rlam3** [comment]
@erperejildo so google dropped support for the SDK? We are now resorting to Cocoapods and native dev?

**Comment by Shadowstep33** [comment]
> Is there a reason why we have to delete the app completely from the simulator/emulator on every build?

@rlam3 I had a problem like this once, it had to do with the Ionic Pro plugin and it attempting to do a background update. It's probably unrelated, but out of curiosity do you have cordova-plugin-ionic installed?

**Comment by rlam3** [comment]
@Shadowstep33 I'm not using any ionic pro plugin. I'm using quasar framework and simply adding admob-free plugin..I'm currently using the interstitial ad and it doesn't show up... on my phone but it shows up in my simulator... don't know why there is a difference here.

**Comment by erperejildo** [comment]
This has been broken already for more than 5 months and it's the main functionality: display ads.

Do we know at least what the problem here is @ratson? If this is a Google thing can we point to it and open an issue maybe on one of their repos?

**Comment by SharkyPT** [comment]
I'm also having a similar problem.

On Android:
- Test IDS -  Banner and Interstitial work fine.
- My AdMob IDS -  Banner and Interstitial work fine.

On iOS
- Test IDS -  Banner and Interstitial work fine.
- My AdMob IDS -  Banner shows black and Interstitial works fine.

On the stats in AdMob the iOS Banner shows 0 impressions but several requests meaning that the requests are reaching adMob.

**Comment by erperejildo** [comment]
that sounds like a different issue. Open a new ticket

**Comment by erperejildo** [comment]
@ratson any update on this?

No pressure, just a friendly reminder, but this has been ticket for a while now

**Comment by erperejildo** [comment]
Well I gave it another workaround and this what I did:

- Updated latest version of this library
- Activated prod mode: https://blog.khophi.co/optimize-ionic-2-app-production/
- Fixed livereload issues: https://stackoverflow.com/questions/40815183/ionic-2-cordova-is-not-available-make-sure-to-include-cordova-js-or-run-in-a-d/42501720
- And this is my working code:
```
     // inside provider constructor
      this.admobFree.banner.config({
        id: this.config.banner.adId,
        isTesting: false,
        autoShow: true,
        bannerAtTop: true
      });
      this.admobFree.banner.prepare();
      this.showBannerFree();

      this.admobFree.interstitial.config({
        id: this.config.interstitial,
        isTesting: false,
        autoShow: false
      });
      this.admobFree.interstitial.prepare();
```

```
async showBannerFree() {
   // this is called by default but you can call it again to refresh the ad 
    try {
      this.admobFree.banner.show()
        .then(() => {
        })
        .catch(e => console.log(e));
    }
    catch (e) {
      console.error(e);
    }
  }

  async showInterstitialFree() {
   // this doesn't work if you want to open it straight away when phone loads but I don't need that
    try {
      if (this.platform.is('cordova')) {
        this.admobFree.interstitial.show();
      }
    }
    catch (e) {
      console.error(e);
    }
  }
```

Hope this helps to everybody!

**Comment by owen-mills** [comment]
What is a provider constructor?

**Comment by erperejildo** [comment]
@owen-mills if you read first message you'll see that I was using `Ionic`. This uses (at least latest version) Angular +2, which also uses TypeScript.

If you're using a different stack and you're having same issue you might have to open a new issue.

https://angular.io/guide/providers

**Comment by merbin2012** [comment]
I have the same error, but the ads are displaying perfectly for mobile internet, but when I using wifi internet the ads are not displaying. Do I need to add any **user-permission**?

**Comment by bgosalci** [comment]
I'm having same issue with my IONIC V1 app.
The production version is working fine, but the new version I'm working on, no ads are being shown.

To make things difficult I no longer have access to the environment I've used for production version as I've switched from windows to mac. 

But I have the production version code, and this are the plugin versions in production version which works fine:
```
  <plugin name="cordova-plugin-admobpro" version="2.20.1"/>
  <plugin name="cordova-plugin-console" version="1.0.1"/>
  <plugin name="cordova-plugin-device" version="1.0.1"/>
  <plugin name="cordova-plugin-google-analytics" version="0.8.1"/>
  <plugin name="cordova-plugin-splashscreen" version="2.1.0"/>
  <plugin name="cordova-plugin-statusbar" version="1.0.1"/>
  <plugin name="ionic-plugin-keyboard" version="2.2.1"/> 
```
And this are the plugins in development environment:
```
    <plugin name="cordova-plugin-admobpro" spec="^2.31.6" />
    <plugin name="cordova-plugin-device" spec="~2.0.2" />
    <plugin name="cordova-plugin-google-analytics" spec="~1.8.6" />
    <plugin name="cordova-plugin-splashscreen" spec="~5.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="~2.4.3-dev" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
```

Tried the admob-ionic-demo, and it behaves same as my app, no ads are shown.

Please help.

**Comment by dalejomen** [comment]
good morning,
I have problems with the plugin cordova-plugin-admobpro when I compile my project and generate the apk for android generates it well. but when I install the apk in my cellphone to application does not load the program is closed.

This was working fine until last week as this plugin used it in several apps.

**Comment by rodrigograca31** [comment]
I'm facing this issue in 2019.
Using Ionic 1 (dont tell me to update...)
yesterday I added [sentry.io](https://sentry.io/) and I'm really happy with it since it's already reporting errors!

To be precise it is reporting the following erros too many times!:
1. `interstitialAd is null, call createInterstitialView first.`
2. `adView is null, call createBannerView first.`

Basically its not displaying ads.... Since the error count is really high for less than 24 hours this is a big issue and it's costing me (and you guys) money. I can even correlate the change to this plugin and the admob impressions going from 10K to 5K without a drop in user sessions...

I can't pinpoint anything specific to these users... Seems to be in all Android OS Versions, Chrome Versions, device types, etc. But this error shows up for me every now and then while I'm developing... and unlike other libraries I dont see ads while developing (not that I want to see them because its against TOS but maybe it has something to do with the diferences between development and prod...?)
(but my users are in )

My code:

```javascript
$ionicPlatform.ready(function () {
...
...
...
if (window.admob !== undefined) {
	admob.banner.config({
		id: 'ID_REMOVE_FOR_PRIVACY',
		autoShow: true
	});

	// Create banner
	admob.banner.prepare();

	// Show the banner
	admob.banner.show();

	admob.interstitial.config({
		id: 'ID_REMOVE_FOR_PRIVACY',
		autoShow: false
	});
	admob.interstitial.prepare(); // .show is called later when its probably ready
}
...
...
...
});
```

**Comment by rodrigograca31** [comment]
Basically the same as issues #60 and #120 and maybe #341 ?
