### ISSUE TITLE
onleavetoAd does not work on IOS for interstitial ads - help wanted pls...

### ISSUE THREAD

**Issue by halkoy** [ratson/cordova-plugin-admob-free#12]
hii,
I am trying to use this plugin but for IOS and interstitial ads onleavetoad event does not fire. It works for banner for IOS. But for android this event works for banner and interstitial.

For IOS and interstitial ads, how can I learn that user clicked the ad or not?

**Comment by ratson** [comment]
On iOS, `adViewWillLeaveApplication` is the hook for this event, do you ever see the event triggered?

Personally, I don't test on iOS a lot, any help / PR would be appreciated.

**Comment by halkoy** [comment]
I didn't see this event on the plugin readme file so I didn't tried. I will try it..
thank you so much for your reply

**Comment by ratson** [comment]
@halkoy I have just published a release, should fix this problem.
Would you confirm if it is fixed?

**Comment by halkoy** [comment]
It is not fixed for IOS. adViewWillLeaveApplication  event was not recognized as an event at javascript for IOS. I found another plugin for IOS which supports this event for IOS.

thnx
