### ISSUE TITLE
Starting on  23 January 2018, we will no longer support Google Mobile Ads (GMA) SDK versions lower than 7.0.0 for Android

### ISSUE THREAD

**Issue by rashnk** [ratson/cordova-plugin-admob-free#129]
Hi, i recived a email from google admob : "Starting on  23 January 2018, we will no longer support Google Mobile Ads (GMA) SDK versions lower than 7.0.0 for Android or iOS. To continue serving mobile ads from AdMob, Ad Exchange, or DFP after this date, please upgrade to the latest Google Mobile Ads SDK"

I am using this plugin on all my apps
Today after noon, none my apps showing ads,only black color at the banner
Should we update anything or the plugin need to be ugrdaed ?

**Comment by ratson** [comment]
@rashnk Would you try the latest version to see if it resolves this issues?

**Comment by rashnk** [comment]
Thank you, i have not updated the plugin,  but Ads were shown after that(ithink it was admob  side issue) , and no issue as of now,
so the latetest version will work after jan 23 right?

**Comment by silu44** [comment]
how to know that your app is in safe side ?
(Ionic 2 app)

**Comment by rashnk** [comment]
@ratson , the notice is in admob site , not in  the app, so we need to  wait till jan 23 to check it works or not, thank yu :+1:

**Comment by Sletheren** [comment]
Anybody has updates concerning this?

**Comment by rashnk** [comment]
i have updated few of my apps with latest cordova and latest of this plugin and uploaded to play store, 
but all my apps still showing ads which im using its older version of this plugin
