### ISSUE TITLE
isTesting: true Not working

### ISSUE THREAD

**Issue by bflopez** [ratson/cordova-plugin-admob-free#13]
I just switched over to this plugin and for some reason I cannot get the isTesting: true option to work for me. It displays real ads regardless. Am I doing something wrong?

    AdMob.setOptions({
        publisherId: admobid,
         isTesting: true
      });      
    AdMob.createBannerView();

**Comment by ratson** [comment]
Which platform are you using? Do you able to run the example?

**Comment by bflopez** [comment]
@ratson This is on iOS 10. I see a message on the console that says request.testDevices: XXXXXXXXXXXXXXXX and then another message that says "To get test ads on this device, call: the same number as before. Hope this helps

**Comment by vintage** [comment]
Same situation for me. Here is my log output:

```
request.testDevices: 23A37F***D83FD05
```

```
<Google> To get test ads on this device, call: request.testDevices = @[ @"23a37f*****d83fd05" ];
```

So it can be as you suggested issue with lowercase/uppercase.

The ad is showing in the application, but it's definitely not a test ad. I've managed to fix the issue by changing the line https://github.com/ratson/cordova-plugin-admob-free/blob/master/src/ios/CDVAdMob.m#L413 to:

`request.testDevices = @[ kGADSimulatorID, deviceId, [deviceId lowercaseString] ];`

Does anyone know if it can impact the library in some "bad way"?
