### ISSUE TITLE
Error after installing this plugin 

### ISSUE THREAD

**Issue by aldoso** [ratson/cordova-plugin-admob-free#131]
**[SOLVED]**

Actually it works like a charm with this code: 
`import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

import { AdMobFree, AdMobFreeBannerConfig, AdMobFreeInterstitialConfig, AdMobFreeRewardVideoConfig } from '@ionic-native/admob-free';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, private admobFree: AdMobFree) {}

  // ionViewDidLoad should start the banner ad as soon as the app is ready
  ionViewDidLoad() {
      const bannerConfig: AdMobFreeBannerConfig = {
        id: '',
        isTesting: false,
        autoShow: true
      };

      this.admobFree.banner.config(bannerConfig);

      this.admobFree.banner.prepare()
        .then(() => {
          // banner Ad is ready
          // if we set autoShow to false, then we will need to call the show method here
        })
        .catch(e => console.log(e));
  }

  showBanner() {
      const bannerConfig: AdMobFreeBannerConfig = {
        id: '',
        isTesting: false,
        autoShow: true
      };

      this.admobFree.banner.config(bannerConfig);

      this.admobFree.banner.prepare()
        .then(() => {
          // banner Ad is ready
          // if we set autoShow to false, then we will need to call the show method here
        })
        .catch(e => console.log(e));
  }

  showInterstitial() {
      const interstitialConfig: AdMobFreeInterstitialConfig = {
        id: '',
        isTesting: false,
        autoShow: true
      };

      this.admobFree.interstitial.config(interstitialConfig);

      this.admobFree.interstitial.prepare()
        .then(() => {
          // banner Ad is ready
          // if we set autoShow to false, then we will need to call the show method here
        })
        .catch(e => console.log(e));
  }

  showRewarded() {
      const rewardVideoConfig: AdMobFreeRewardVideoConfig = {
        id: '',
        isTesting: false,
        autoShow: true
      };

      this.admobFree.rewardVideo.config(rewardVideoConfig);

      this.admobFree.rewardVideo.prepare()
        .then(() => {
          // banner Ad is ready
          // if we set autoShow to false, then we will need to call the show method here
        })
        .catch(e => console.log(e));
  }

}
`

**Comment by aldoso** [comment]
it worked it I add a button with click function on home.html
`<ion-button (click)="adShow()">Click me!</ion-button>`
and on home.ts this code: 

`import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

import { AdMobFree} from '@ionic-native/admob-free';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, private admobFree: AdMobFree) {

  }

  const bannerConfig: AdMobFreeBannerConfig = {
    // add your config here
    // for the sake of this example we will just use the test config
    id: '',
    isTesting: true,
    autoShow: true
  };


 adShow(){
  this.admobFree.banner.config(this.bannerConfig);

  this.admobFree.banner.prepare()
    .then(() => {
      // banner Ad is ready
      // if we set autoShow to false, then we will need to call the show method here
    })
    .catch(e => console.log(e));
  }


}
`

**Comment by ratson** [comment]
Close as if it was solved.
