### ISSUE TITLE
Event not firing at iOS devices

### ISSUE THREAD

**Issue by momikus** [ratson/cordova-plugin-admob-free#133]
Plugin is great. However, "admob.rewardvideo.events.REWARD" event is not firing at iOS devices.

**Comment by faytekin** [comment]
+1

**Comment by sumolex** [comment]
Hi, thanks for the plugin! But, what about "admob.rewardvideo.events.REWARD" it doesn`t work! :(

**Comment by anacierdem** [comment]
It does work for me, how do you use it exactly?
