### ISSUE TITLE
Version 0.13.0 has build error

### ISSUE THREAD

**Issue by wo-github** [ratson/cordova-plugin-admob-free#135]
After Update the version to 0.13.0 I can`t build the app on Android.
This is the error:

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzex;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I need to use this plugin https://github.com/dpa99c/cordova-android-play-services-gradle-release, to prevent the error.

**Comment by merbin2012** [comment]
install lowest version of this plugin
cordova plugin add cordova-plugin-admob-free@0.12.1

**Comment by kumaravel95** [comment]
just try to remove the platform and add the platform again.
