### ISSUE TITLE
Set Admob AppId

### ISSUE THREAD

**Issue by wo-github** [ratson/cordova-plugin-admob-free#144]
Hello,
how could I set the AppId with this plugin?
https://developers.google.com/admob/android/quick-start
MobileAds.initialize(this, "YOUR_ADMOB_APP_ID");
Or which AppId is sending to Admob?
Please have a look here https://support.google.com/admob/answer/7356427?hl=de&ref_topic=7384409
To initialize the add, you need the Admob App-Id and the Banner-Id, but this plugin only set the Banner-Id.
How to set the Admob App-Id in a native App is described here https://developers.google.com/admob/android/quick-start.
Please add the possibility to set the Admob AppId.

I discuss the topic with google support and the admob appid is required to initialize the banner.
The request of a Ad without AdMob App-Id could work, but will be discontinued soon.

**Comment by Gillardo** [comment]
any news on this?

**Comment by BLukassen** [comment]
I have the same request. In the PluginCode I cant find any init of the MobileAds:
      MobileAds.initialize(this, "YOUR_ADMOB_APP_ID");
It seems it is missing.

**Comment by rlam3** [comment]
@wo-github @Gillardo  Were you able to figure this out?

**Comment by Gillardo** [comment]
@rlam3 Nope i didnt.

**Comment by wo-github** [comment]
I add the code without setting the appid and it works.

**Comment by rlam3** [comment]
@wo-github are you developing a cordova/vue js app? Do you mind sharing where you implement/integrate the configs and how to display the banner? I'm having trouble in getting this to work with vue js app. 

This is my repo
https://bitbucket.org/rlam3/011_cordova_admob

**Comment by wo-github** [comment]
@rlam3 It`s a Ionic app, with admob free plugin https://ionicframework.com/docs/native/admob-free/

**Comment by wo-github** [comment]
@rlam3 no, sorry I can`t help you.

**Comment by puffnir** [comment]
Any update about this issue?
Is it safe to use this plugin without setting App Id?

**Comment by ABDULAZIZ94** [comment]
hello, im facing hard time to load the app when stting isTesting=false
