### ISSUE TITLE
Error in Cordova 7 ionic project

### ISSUE THREAD

**Issue by rashnk** [ratson/cordova-plugin-admob-free#150]
Cordova 7 was released , i removed android platform and added again, removed admob-free plugin and added again, run cordova clean, and ran build command as 
`ionic cordova build android`, now im getting error as in the image
![admob](https://user-images.githubusercontent.com/12730428/35050401-c199a5b0-fbc8-11e7-9b59-4b3c21b49409.PNG)
`**AdMob.java:27: error: package name.ratson.cordova.admob.banner does not exist**`
is the package name not correct, why im i getting this error?

**Comment by RenaudROHLINGER** [comment]
Temporally you can
```cordova plugin add https://github.com/RenaudROHLINGER/lycwed-cordova-plugin-admob-free```

my repo is fixed for the latest version. I can't really PR this repo atm since this is a specific cordova 7.0 issue
