### ISSUE TITLE
error: package name.ratson.cordova.admob.banner does not exist

### ISSUE THREAD

**Issue by geniusbabak** [ratson/cordova-plugin-admob-free#153]
I was having this error:
`error: package name.ratson.cordova.admob.banner does not exist import name.ratson.cordova.admob.banner.Banner Executor;`

My problem solved with:

1. Remove cordova android from your app ionic cordova platform rm android;
2. Add cordova-android 6.3.0 cordova platform add android@6.3.0;

**Comment by supermaker** [comment]
Very very thanks @geniusbabak

**Comment by dawuwu** [comment]
"I managed to solve the issue by copying the sources from platforms/android/src/name/ratson/cordova/admob/* to platforms/android/app/src/main/java/name/ratson/cordova/admob/."

source:
https://forum.ionicframework.com/t/admobfree-error/116011/5

**Comment by RenaudROHLINGER** [comment]
If you wants to you the latest version of cordova & cordova-android : 
```cordova plugin rm cordova-plugin-admob-free``` -->
```cordova plugin add https://github.com/RenaudROHLINGER/lycwed-cordova-plugin-admob-free```

Repo is fixed for the latest version. I can't PR this repo at this moment since this is a specific cordova 8.0 issue

**Comment by luisameglio** [comment]
@dawuwu te mamaste!!! it worked!

**Comment by srikanth-wgl** [comment]
Fixed in PR #189 for both cordova 7 and cordova 8. Try using latest version of the plugin (v0.15.0).
