### ISSUE TITLE
No support for rewarded video ads?

### ISSUE THREAD

**Issue by sabrielle6** [ratson/cordova-plugin-admob-free#16]
would love to see this added

**Comment by vintage** [comment]
I agree that it would be great to have reward videos integrated into lib. There is just one problem with that - AdMob itself doesn't serve any reward videos and it needs external providers such as AdColony, InMobi, Unity Ads etc.

So first thing to focus on is to bring easy way to integrate with ad mediators. The discussion is available here - https://github.com/ratson/cordova-plugin-admob-free/issues/7

**Comment by raulpopi** [comment]
Hello,

I've prepared a code to test the rewarded videos, but I need a test id and a mediaton to allow it. 
@vintage do you know which one I can use?

My unproven code is here https://github.com/raulpopi/cordova-plugin-admob-free

**Comment by vintage** [comment]
@raulpopi: The code looks promising! Unfortunately as I said in previous comment the `cordova-plugin-admob-free` doesn't have any mediation network which supports reward videos AFAIK. I'll have more time in December so would start investigating how to write mediations on my own. Maybe @becvert can help here?

**Comment by raulpopi** [comment]
@vintage many thanks, one thing, which of the providers you recommend, that I will try to look to see if I can do anything with any of them. Which do you think is best for any type of application, not just games?

**Comment by becvert** [comment]
rewarded videos are supported out of the box by just a few mediation networks 
 [supported ad formats](https://firebase.google.com/docs/admob/android/mediation-networks#supported-ad-formats)

To write your own mediation plugins, all the resources are here:
[supported ad networks](https://firebase.google.com/docs/admob/android/mediation-networks#supported-ad-network)
Have a look too at:
[cordova-plugin-admob-mediation-facebook](https://github.com/becvert/cordova-plugin-admob-mediation-facebook)

good luck!

**Comment by raulpopi** [comment]
Hello, thank you @becvert 

One doubt, I'm looking at the facebook plugin, and I do not see how the cordova-plugin-admob-free plugin is connected to the facebook plugin. That is, in code where your plugin would be called?

**Comment by becvert** [comment]
There's no direct connection between the two.
The facebook plugin just add the mediation adapter class in your project.
The Google Admob SDK looks for mediation adapters in the classpath at runtime.
If an adapter it's there, third-party ads can be displayed otherwise it fallbacks to another mediation network or admob only.

**Comment by raulpopi** [comment]
Great @becvert, now I understand, thank you very much for the explanation.

It's just that I've been reviewing other code and seeing connections, and I was getting confused.
