### ISSUE TITLE
Build faild on build.phonegap.com with phonegap version 8.0.0

### ISSUE THREAD

**Issue by Filavision** [ratson/cordova-plugin-admob-free#162]
Build faild at build.phonegap.com with new phonegap version "cli-8.0.0" and cordova-plugin-admob-free version 0.13. from npm. Error log for android says:

`/app/src/main/java/name/ratson/cordova/admob/AdMob.java:27: error: package name.ratson.cordova.admob.banner does not exist
import name.ratson.cordova.admob.banner.BannerExecutor;
                                       ^
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:28: error: package name.ratson.cordova.admob.interstitial does not exist
import name.ratson.cordova.admob.interstitial.InterstitialExecutor;
                                             ^
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:29: error: package name.ratson.cordova.admob.rewardvideo does not exist
import name.ratson.cordova.admob.rewardvideo.RewardVideoExecutor;
                                            ^
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:44: error: cannot find symbol
    private BannerExecutor bannerExecutor = null;
            ^
  symbol:   class BannerExecutor
  location: class AdMob
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:45: error: cannot find symbol
    private InterstitialExecutor interstitialExecutor = null;
            ^
  symbol:   class InterstitialExecutor
  location: class AdMob
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:46: error: cannot find symbol
    private RewardVideoExecutor rewardVideoExecutor = null;
            ^
  symbol:   class RewardVideoExecutor
  location: class AdMob
/app/src/main/java/com/alexdisler/inapppurchases/IabHelper.java:230: error: package IInAppBillingService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);
                                               ^
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:70: error: cannot find symbol
            bannerExecutor = new BannerExecutor(this);
                                 ^
  symbol:   class BannerExecutor
  location: class AdMob
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:73: error: cannot find symbol
            interstitialExecutor = new InterstitialExecutor(this);
                                       ^
  symbol:   class InterstitialExecutor
  location: class AdMob
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:76: error: cannot find symbol
            rewardVideoExecutor = new RewardVideoExecutor(this);
                                      ^
  symbol:   class RewardVideoExecutor
  location: class AdMob
Note: /app/src/main/java/org/apache/cordova/splashscreen/SplashScreen.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
12 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
39 actionable tasks: 39 executed
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/app/src/main/java/com/alexdisler/inapppurchases/IabHelper.java:33: error: package com.android.vending.billing does not exist
import com.android.vending.billing.IInAppBillingService;
                                  ^
/app/src/main/java/com/alexdisler/inapppurchases/IabHelper.java:103: error: cannot find symbol
    IInAppBillingService mService;
    ^
  symbol:   class IInAppBillingService
  location: class IabHelper
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:27: error: package name.ratson.cordova.admob.banner does not exist
import name.ratson.cordova.admob.banner.BannerExecutor;
                                       ^
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:28: error: package name.ratson.cordova.admob.interstitial does not exist
import name.ratson.cordova.admob.interstitial.InterstitialExecutor;
                                             ^
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:29: error: package name.ratson.cordova.admob.rewardvideo does not exist
import name.ratson.cordova.admob.rewardvideo.RewardVideoExecutor;
                                            ^
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:44: error: cannot find symbol
    private BannerExecutor bannerExecutor = null;
            ^
  symbol:   class BannerExecutor
  location: class AdMob
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:45: error: cannot find symbol
    private InterstitialExecutor interstitialExecutor = null;
            ^
  symbol:   class InterstitialExecutor
  location: class AdMob
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:46: error: cannot find symbol
    private RewardVideoExecutor rewardVideoExecutor = null;
            ^
  symbol:   class RewardVideoExecutor
  location: class AdMob
/app/src/main/java/com/alexdisler/inapppurchases/IabHelper.java:230: error: package IInAppBillingService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);
                                               ^
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:70: error: cannot find symbol
            bannerExecutor = new BannerExecutor(this);
                                 ^
  symbol:   class BannerExecutor
  location: class AdMob
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:73: error: cannot find symbol
            interstitialExecutor = new InterstitialExecutor(this);
                                       ^
  symbol:   class InterstitialExecutor
  location: class AdMob
/app/src/main/java/name/ratson/cordova/admob/AdMob.java:76: error: cannot find symbol
            rewardVideoExecutor = new RewardVideoExecutor(this);
                                      ^
  symbol:   class RewardVideoExecutor
  location: class AdMob
Note: /app/src/main/java/org/apache/cordova/splashscreen/SplashScreen.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

**Comment by MBuchalik** [comment]
This could be related to #143 (but I am not sure about this).

**Comment by k00na** [comment]
This helped me pass this error: 

https://forum.ionicframework.com/t/admobfree-error/116011/7

**Comment by X0t0** [comment]
@k00na bro if you can help me i'm getting this error for 3 days and i don't know why : 
`Dex: Error converting bytecode to dex: Cause: PARSE ERROR: class name (com/google/android/gms/base/R) does not match path (Com/google/android/gms/base/R.class) ...while parsing Com/google/android/gms/base/R.class`

**Comment by k00na** [comment]
Hmm... i'm not sure if I can really help cuz I don't know the whole cause of your problem. 

Based on your error i would try: 
1)  chaning the first letter in the package name "Com/google/android/gms/base/R.class" to be lower case just as it is in the first package and remove .class at the end of it so you get com/google/android/gms/base/R
2) if that doesn't work it could be something with the dex thingy :D check this for solutions: https://stackoverflow.com/questions/34352591/android-error-converting-byte-to-dex

Hope you make it work.

**Comment by X0t0** [comment]
@k00na it doesn't the problem is i can build my app when i remove the admob free plugin , and when i add it i can't.

**Comment by X0t0** [comment]
@k00na  this is the whole error
![screenshot 2](https://user-images.githubusercontent.com/19890345/36356721-a36db2c8-14ed-11e8-94f9-f0893d1b0427.png)

**Comment by X0t0** [comment]
@k00na if you can share with your environment info , ionic info and what you’re installing in sdk , I think it’s problem related to sdk

**Comment by Filavision** [comment]
Hallo!

Wir sind bis einschließlich 13.04.2018 im Urlaub, weshalb sich unsere Antwort etwas verzögern kann.

Viele Grüße,
Dipl.-Ing. Vicki Langner & Steven Fiedler

Filavision Internetagentur
Fiedler & Langner GbR
Am Judenkirchhof 7
30167 Hannover

Tel: 0511/4742398
www.filavision.de

Diese E-Mail wurde automatisch erstellt.
