### ISSUE TITLE
Can I only test the production banners after I release my app?

### ISSUE THREAD

**Issue by evertondanilo** [ratson/cordova-plugin-admob-free#166]
Guys, sorry about this question, but I create an app that it is in develop mode until now, so I created the bannerAd config with  "isTesting=true". Now, I am trying to get a real Banner Ad from Admob server, then I changed the isTesting flag to false. 
As a result, I'm getting the error message: "No Fill from Ad Server".

My question is: Can I only test the production banners after I release my app?

**Comment by skekeu** [comment]
I have a similar issue.
No Ads displayed when isTesting is false, but I get no error at all. Any code I put inside the prepare() promise is fired , but no Ads displayed.

**Comment by steinjonathan** [comment]
I'm having this same issue.
How did you @evertondanilo and @skekeu solved it?

**Comment by skekeu** [comment]
Didn't solve this yet.
Still waiting for some update on this issue.

**Comment by skekeu** [comment]
Finally I solved this issue!

Since my code seemed to be right, as the test Ads were working, I went back to my Admob account and found out that I had missing payment info.

As soon as I added my address on the payment page, my live Ads started being served.

I have tested my app on Android (emulator and device) and IOS (emulator only) and the Live Ads are being served with no problem on both.

**Comment by evertondanilo** [comment]
I read on another site/thread that we need to verify the address on adsense page, then I checked this page here and I needed to verify my address as well. 
Google will send a letter to my address with a PIN number...

I'm still waiting to get this pin and sort this issue.

**Comment by skekeu** [comment]
I think my address was already verified with adsense, but still I had to add my address on Admob payment page.

**Comment by Tymofek** [comment]
I had no errors and no ad displayed.
Thx to @skekeu i went back to admob's site and there was a warning telling me to fill the address data.
in minutes i checked my app and yes there was an admob test ad.

checklist:

- [ ] you sign for adMob new account.
- [ ] need to set the payment info
- [ ] you need to create an ad (banner or others, you get an id here)
- [ ] use the simple code example for config use the baner id not the app id 
```
id:"ca-app-pub-x.*/x.*",//this is the banner's ID
      isTesting: false,
      autoShow: true)
```
- [ ] call config(conf) and prepare() (if you use autoShow you dont need to call show())
- [ ] wait a couple of minutes, make sure the app its closed, open it and... voilà!

Hope this helps others.

**Comment by skekeu** [comment]
Nice @Tymofek !
