### ISSUE TITLE
AdMob Free Plugin on Ionic 3

### ISSUE THREAD

**Issue by hamdanihamza** [ratson/cordova-plugin-admob-free#176]
Hey Everyone, i installed admob free plugin on my ionic 3 project, and typed this code 
```
async showBanner() {
		try {
		const bannerConfig: AdMobFreeBannerConfig = {
			id: 'ca-app-pub-APP_ID',
			isTesting: false,
			autoShow: true,
		};
		this.admobFree.banner.config(bannerConfig);

		const result = await this.admobFree.banner.prepare();
		console.log(result);
		}
		catch (e) {
			console.log(e);
		}
	}
```

but the ads aren't showing ... i'm deploying on a real device with android version 6.0.

Hope to get some help, thanks !

**Comment by prantikv** [comment]
Are you getting any errors? Ads take up some time to show if they are newly created ad units.

**Comment by hamdanihamza** [comment]
@prantikv no its fixed thanks :D, i reinstalled the plugin and its working fine now !

**Comment by erperejildo** [comment]
@hamdanihamza close the ticket if it's working.

Duplicated: https://github.com/ratson/cordova-plugin-admob-free/issues/119
