### ISSUE TITLE
Does it support ad from other ad networks (configure in admob) like applovin?

### ISSUE THREAD

**Issue by zeroonea** [ratson/cordova-plugin-admob-free#180]

**Comment by ivanov84** [comment]
**Mediation connection algorithm:**

Android:
1. create file build_extras
2. put there code:

repositories {
    maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
}

android {
    dexOptions {
        jumboMode true
    }
    defaultConfig {
        multiDexEnabled true
    }
}

dependencies {
    //install unity mediation
    compile 'com.unity3d.ads:unity-ads:2.2.0'
    compile 'com.google.ads.mediation:unity:2.2.0.0'

    //install mytarget mediation
    compile 'com.my.target:mytarget-sdk:4.7.+'

    //install unity mopub
    compile('com.mopub:mopub-sdk:4.20.+@aar') {
        transitive = true
    }
    compile 'com.google.ads.mediation:mopub:4.20.+'

    //install inmobi mediation
    compile 'com.inmobi.monetization:inmobi-ads:7.+'
    compile 'com.google.ads.mediation:inmobi:7.+'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.android.support:recyclerview-v7:24.0.0'
}

3. add to config.xm:
<hook src="build_extras.js" type="before_build" />

4. build app



iOs:
1. add to platforms\ios\Podfile:
target 'MyApp' do
    pod 'GoogleMobileAdsMediationInMobi'
    pod 'GoogleMobileAdsMediationUnity'
    pod 'GoogleMobileAdsMediationMoPub'
    pod 'GoogleMobileAdsMediationMyTarget'
end

2. run command: "pod install" in platforms\ios directory

3. build app

**Comment by tominou** [comment]
Yes it does support Admob mediation. For so, you need to add other networks sdk to your project.
