### ISSUE TITLE
Admob banner and setting safe-area-inset (iOS - iPhone X)

### ISSUE THREAD

**Issue by aabdolla** [ratson/cordova-plugin-admob-free#182]
Hello,

I am using the latest cordova, ionic and admob free plugin. I am running into the issue of the admob banner being blocked by the bottom corners rounding in on the iPhone X. How can I apply the safe-area-inset to the admob banner so I can bring it up a bit from the bottom? Should I be running into this issue?

Thanks!

**Comment by anacierdem** [comment]
See #121

**Comment by ratson** [comment]
https://github.com/ratson/cordova-plugin-admob-free/pull/186 should address this, free feel to reopen if it does not.
