### ISSUE TITLE
Is it possible to display the interstitial ad during the splash screen?

### ISSUE THREAD

**Issue by weltonpagassini** [ratson/cordova-plugin-admob-free#185]
![unnamed](https://user-images.githubusercontent.com/37492656/37562240-823622a6-2a42-11e8-957c-4d16616157e4.jpg)
Is it possible to display the interstitial ad during the splash screen?
When you try to do this, it closes the splash screen and displays the home of the app before displaying the interstitial.

**Comment by ratson** [comment]
@weltonpagassini You could simulate the effect by displaying the ad on device ready event, but since ads are loaded asynchronously and maybe fail, this may result a long loading time for your users.
