### ISSUE TITLE
App exit on backbutton, if ad banner overlay=false (on ionic)

### ISSUE THREAD

**Issue by raulpopi** [ratson/cordova-plugin-admob-free#19]
Whenever the app was at main page or other page, when i click onHardwareBack it will direct exit the apps without going back previous state or prompt toast message.

If overlay=true work perfectly.

When you load the banner, it is as if the focus to stay somewhere.

**Comment by raulpopi** [comment]
hello, 
I just solve, the problem is that the 'webview' does not have focus to display the banner. Only in android.

in
```
if (bannerAtTop) {
  parentView.addView(adView, 0);
} else {
  parentView.addView(adView);
}
parentView.bringToFront();
parentView.requestLayout();
```

add
`parentView.requestFocus();`

getting
```
if (bannerAtTop) {
  parentView.addView(adView, 0);
} else {
  parentView.addView(adView);
}
parentView.bringToFront();
parentView.requestLayout();
parentView.requestFocus();
```

**Comment by ratson** [comment]
@raulpopi Thanks, would you put this into a PR?
If not, I could include it myself later.

**Comment by raulpopi** [comment]
Hello, I've never done a PR ... I have to study how it's done.
For now if you want to include you when you can, as is faster.
Thanks

**Comment by ratson** [comment]
@raulpopi Released the fix. For creating pull request, you may refer to https://help.github.com/articles/creating-a-pull-request/

**Comment by erperejildo** [comment]
@ratson I'm facing the same issue right now

**Comment by etcho** [comment]
I don't have much hope, but I'm having the exactly same problema. Is there a official solution?

**Comment by shafimcs** [comment]
@erperejildo is this fixed?

**Comment by erperejildo** [comment]
I don't know @shafimcs I'm not using this anymore
