### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by ManoloPololo** [ratson/cordova-plugin-admob-free#195]
Hello, I'm getting an error when trying to update my app. The steps that I followed are the next ones:
- I open the windows cmd and type:
`cd *hybrid app directory*`
`cordova build android`
- Then, it loads and I get this error:
```
Error: cmd: Command failed with exit code 1 Error output:
C:\Users\MyName\Documents\AppName\platforms\android\src\name\ratson\cordova\admob\rewardvideo\RewardVideoListener.java:13: error: RewardVideoListener is not abstract and does not override abstract method onRewardedVideoCompleted() in RewardedVideoAdListener
class RewardVideoListener implements RewardedVideoAdListener {
^
```
- More details:
```
`* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`
```

Can you, please, help me?
Thanks in advance!

**Comment by tominou** [comment]
Are you using the latest version of the plugin?

**Comment by ManoloPololo** [comment]
Maybe I don't... I don't know. How do I update it?

**Comment by tominou** [comment]
Simply uninstall/reinstall it ^^ It should fix your issue

**Comment by tominou** [comment]
No reply so considered as fixed. Please reopen if it is not.
Thank you.

**Comment by nilesh52** [comment]
getting same error.
please provide information to resolve that

**Comment by nilesh52** [comment]
reinstall/ uninstall is not working

**Comment by nilesh52** [comment]
Getting Below Error

:app:compileDebugJavaWithJavac
S:\IonicDemo\admob\platforms\android\app\src\main\java\name\ratson\cordova\admob
\rewardvideo\RewardVideoListener.java:90: error: method does not override or imp
lement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error


FAILURE: Build failed with an exception.

* What went wrong:
FAILED
27 actionable tasks: 1 executed, 26 up-to-date
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.
