### ISSUE TITLE
Mediation: Facebook Audience Network

### ISSUE THREAD

**Issue by tominou** [ratson/cordova-plugin-admob-free#199]
Can mediation with Facebook Audience Network work with this plugin?
I can't manage to display FAN ads. Nothing from FAN shows up despite hundreds thousands requests, i still got 0 impressions.

I added `cordova.system.library.13=com.facebook.android:audience-network-sdk:4.27.1
cordova.system.library.14=com.google.ads.mediation:facebook:4.27.1.0
` to `project.properties` and set up mediation group in the Admob console. I see the requests on FAN's console, but impression stays at 0 for more than 2 weeks.

Anyone knows how i can make it work?

Thank you

**Comment by jonatarussi** [comment]
Did you solve it?
