### ISSUE TITLE
the admob-free will not work in the xdk 3357 

### ISSUE THREAD

**Issue by GitCod-Man** [ratson/cordova-plugin-admob-free#2]
when I use the old xdk version ,it works better. but in the new xdk version,I have add the plugin into it ,when I build my app and download it, the ad not show,

**Comment by ratson** [comment]
Thank you for the report.

I have no experience about xdk, don't know how to setup it. If you could create a repo. with instructions about how to produce the problem, I would take a look.

Any pull request to fix it is welcome.

**Comment by hypersurge** [comment]
I had success with XDK 3357, however not initially.  To resolve I built a minimalist example noting the Cordova network request whitelist needed to be very permissive.  I also noted that for iOS test-mode it is necessary to include the device hash in CDVAdMob.m (~line 750).  I also changed AdMob.js prepareInterstitial() to pass "args" onwards to the internal functions.  I cannot say concretely which of these steps made the difference, but I hope my comments can help.

**Comment by ratson** [comment]
@hypersurge Thank you for the input, I have changed the code according to your comment.

@GitCod-Man Would you let me know if it fixes your problem?

**Comment by ratson** [comment]
@GitCod-Man Do you have a chance to try out the latest version?

**Comment by ratson** [comment]
Closing this because no reply. Free to reopen if needed.
