### ISSUE TITLE
The screen go automatically up and down

### ISSUE THREAD

**Issue by manzajaro** [ratson/cordova-plugin-admob-free#20]
The screen go automatically up and down (see video).
https://drive.google.com/open?id=0B-A3-k4oz8IKRUR2Qi13SHV1TTQ

`document.addEventListener('onReceiveAd', function() {
      AdMob.showAd(true);
    });
`

`AdMob.setOptions({`
        publisherId: admobid.banner,
        interstitialAdId: admobid.interstitial,
        bannerAtTop: true,  // set to true, to put banner at top
        overlap: false,  // set to true, to allow banner overlap webview
        offsetTopBar: false,  // set to true to avoid ios7 status bar overlap
        isTesting: false,  // receiving test ad
        autoShow: false,  // auto show interstitial ad when loaded
      `});`

`if(AdMob) AdMob.createBannerView();
if(AdMob) AdMob.prepareInterstitial({adId: admobid.interstitial,autoShow: false});`

It works for me well, but a customer has complained that happens about the video.

**Comment by ratson** [comment]
@manzajaro I could not re-create the problem. It would be best you could provide an sample problem for me to look into.

Closing this as nothing is actionable.
