### ISSUE TITLE
admob.rewardvideo.events.CLOSE not fired after a test reward video is displayed

### ISSUE THREAD

**Issue by TerryZH** [ratson/cordova-plugin-admob-free#206]
Thanks for this great SDK!

I was able to display a test reward video on my emulator after invoking the `config`, `prepare` and `show` functions. I saw `LOAD` event as a result of `prepare` and `OPEN` event as a result of `show`. 

However, I do not see any event fired if I close the reward video before or after the video finishes. Knowing that `REWARD` event is fired only on real devices (correct me if wrong), I was expecting the `CLOSE` event.

**Comment by ivanov84** [comment]
use full string: admob.rewardvideo.events.LOAD_FAIL
