### ISSUE TITLE
Black but clickable ads

### ISSUE THREAD

**Issue by BlackHo** [ratson/cordova-plugin-admob-free#22]
Hi,

In last 7 days I noticed that ads are mostly shown black on my test device Android 4.0.4 (app uses plugin crosswalk 1.8.0), they are black but clickable and leads to correct page, but banner is shown only after calling some alert() popup:
1) It's black when loaded: http://prnt.sc/d2oyxb
2) After calling alert() it shows immediately: http://prnt.sc/d2ozcp

I guess that issue is caused due some rendering or layer layout problem, so I wonder is there a way to push it again with adding some code to AdMob.java code?

Thanks!

**Comment by ratson** [comment]
@BlackHo 
Would you confirm if the [example](https://github.com/ratson/cordova-plugin-admob-free/tree/master/example) is working for you?
If yes, I would test if `crosswalk` caused the problem.
It would be best if you could create a sample project showing the problem.

**Comment by BlackHo** [comment]
I updated admob plugin to 0.4.0 and it was throwing some error while building apk, so I decided to check android studio, sdk and jdk versions too... I updated them all as they were out-of-date and rebuilt apk without issues, and ads are working now.
Thanks a lot for effort and this awesome plugin :)

**Comment by code4youreal** [comment]
Hi! I have the same problem, if I use the new plugin just loading and not build under intel XDK,

**Comment by BlackHo** [comment]
Seems that banner is not always generated... I'm getting error 0 on receiving banner or interstitial ad (seems it's ERROR_CODE_INTERNAL_ERROR), but it's interesting that it's working sometimes but again sometimes it's not working at all.
