### ISSUE TITLE
Phonegap: black banner not clickable on ios

### ISSUE THREAD

**Issue by bx67212** [ratson/cordova-plugin-admob-free#221]
I use CLI 7.1.0
Current situation:
Android everything work fine
Ios prod banner appear black and not clickable

**Comment by bx67212** [comment]
I found the problem: I commented test mode....

**Comment by MBuchalik** [comment]
Just for clarification: Did you have to change something in the code of this plugin? (To me, it sounds like you found a bug, so maybe we can fix it for all users?)
