### ISSUE TITLE
Can't build... Desugar error!

### ISSUE THREAD

**Issue by braglin** [ratson/cordova-plugin-admob-free#222]
Hi everyone!

I'm trying to build my app and I'm getting the following error message: 

    app:transformClassesWithDesugarForReleaseException` in thread "main" java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':app:transformClassesWithDesugarForRelease'.
    > com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar`

This is my config.xml file:
    
```
<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="18" id="onethinonehdr.bragot.ad.spanish" version="1.1.2" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>1000in100 Espanhol</name>
    <description>1000 palabras 100 dias</description>
    <author>Bragot!</author>
    <content src="index.html" />
    <platform name="android">
        <preference name="android-minSdkVersion" value="16" />
        <preference name="android-targetSdkVersion" value="19" />
        <preference name="android-installLocation" value="auto" />
        <preference name="Fullscreen" value="true" />
        <preference name="Orientation" value="portrait" />
        <preference name="AndroidLaunchMode" value="singleTop" />
    </platform>
    <splash density="xhdpi" height="960" orientation="portrait" platform="android" src="package-assets/720.png" width="720" />
    <splash density="hdpi" height="640" orientation="portrait" platform="android" src="package-assets/640.png" width="480" />
    <splash density="mdpi" height="470" orientation="portrait" platform="android" src="package-assets/470.png" width="320" />
    <splash density="ldpi" height="426" orientation="portrait" platform="android" src="package-assets/426.png" width="320" />
    <icon density="xhdpi" height="96" platform="android" src="package-assets/96.png" width="96" />
    <icon density="ldpi" height="36" platform="android" src="package-assets/36.png" width="36" />
    <icon density="hdpi" height="72" platform="android" src="package-assets/76.png" width="72" />
    <icon density="mdpi" height="48" platform="android" src="package-assets/46.png" width="48" />
    <feature name="GAPlugin">
        <param name="android-package" value="com.adobe.plugins.GAPlugin" />
    </feature>
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <plugin name="cordova-plugin-market" spec="git+https://github.com/xmartlabs/cordova-plugin-market.git" />
    <plugin name="cordova-admobsdk" spec="^1.0.4" />
    <plugin name="de.appplant.cordova.plugin.local-notification" spec="^0.8.5" />
    <plugin name="cordova-plugin-tts" spec="^0.2.3" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.2.1" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="^2.3.0">
        <variable name="XWALK_VERSION" value="23+" />
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
        <variable name="XWALK_MODE" value="embedded" />
        <variable name="XWALK_MULTIPLEAPK" value="true" />
    </plugin>
    <plugin name="cordova-plugin-admob-free" spec="^0.17.0" />
    <plugin name="cordova-android-support-gradle-release" spec="^1.4.2" />
</widget>
```

And my build.gradle...

```
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
    dependencies {

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.android.tools.build:gradle:3.0.0'
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
    //This replaces project.properties w.r.t. build settings
    project.ext {
      defaultBuildToolsVersion="25.0.2" //String
      defaultMinSdkVersion=19 //Integer - Minimum requirement is Android 4.4
      defaultTargetSdkVersion=26 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=26 //Integer - We ALWAYS compile with the latest by default
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

What I'm missing?

Tks!

**Comment by braglin** [comment]
Please... close this issue, it's already solved!

**Comment by tennist** [comment]
@braglin you can close this issue yourself by creating a new comment and clicking the button to comment and close instead of the comment button.  Please do this.

**Comment by lfreneda** [comment]
How did you solve it @braglin?

**Comment by jb-72** [comment]
Had the same issue, `cordova clean` fixed it.
