### ISSUE TITLE
Android. "admob.rewardvideo.events.REWARD" doesn't fired. 

### ISSUE THREAD

**Issue by kurtiev** [ratson/cordova-plugin-admob-free#225]
iOS - i'm using real device and emulator, so listener works as expected.
Android - builded with next command - 

> ionic cordova build --release --prod android

 So on android event lisnener never fired, tested only on real device.

```
this.admobFree.on("admob.rewardvideo.events.REWARD").subscribe((data) => {
        
})
```

Any ideas?
The rest events on android  works good.

**Comment by kurtiev** [comment]
Resolved:       

```
document.addEventListener('admob.rewardvideo.events.REWARD', () => {
          alert("GIVE USER A REWARD HERE");
})
```

**Comment by cagb80** [comment]
> Resolved:
> 
> ```
> document.addEventListener('admob.rewardvideo.events.REWARD', () => {
>           alert("GIVE USER A REWARD HERE");
> })
> ```

I'snt the best solution but work! TY!
