### ISSUE TITLE
Ads showing fine on ios, android rarely shows.

### ISSUE THREAD

**Issue by joe-scotto** [ratson/cordova-plugin-admob-free#226]
I'm using the following code to display ads on my app, it is working fine on ios and without issue but when I hop into android, only sometimes will the ad display. Out of 50 launches it has shown only once or twice. I'm testing on an nexus 5x emulator.

```
  var admobId = platform.is('ios') ? "iosid" : "androidid";

  const bannerConfig: AdMobFreeBannerConfig = { 
    id: admobId, 
    autoShow: true, 
    isTesting: true 
  };

  this.admobFree.banner.config(bannerConfig);

  this.admobFree.banner.prepare().then((e) => { 
    console.log(e) 
  }).catch(e => console.log(e));
```

**Comment by joe-scotto** [comment]
@tennist On iOS I am consitently getting ads. Is the proper way of doing things to have two different ad ids for ios and android? I did just create the android today so that would make sense but I'm rarely getting anything even with isTesting set to true.

**Comment by tennist** [comment]
Yes you must create separate ads.  In admob you have to create an Android app and iOS app.  You then create banners or interstitial sin each of these apps.  Then in your app you must determine if the device is an Android or iOS device and use the appropriate ad I’d.

**Comment by joe-scotto** [comment]
That makes sense. I tested on an actual device using my iOS id and the ads show on Android so I'm thinking it's an emulator issue now.

**Comment by tennist** [comment]
Your Android id will work soon.  Per admob you should be using different ids for the different devices but I think the way this plugin works allows the ids to work for either.  Best to use the right method though.  Please close this issue if you have no further comment.

**Comment by joe-scotto** [comment]
Yeah, this should work.
