### ISSUE TITLE
Change black background behind ad on iPhone X?

### ISSUE THREAD

**Issue by joe-scotto** [ratson/cordova-plugin-admob-free#228]
Is there a way that I can control the color of the background behind the ad? On every other device it looks fine, just on iPhone x it gets this gross black background.

<img width="324" alt="screen shot 2018-06-04 at 6 57 36 pm" src="https://user-images.githubusercontent.com/8194147/40945994-437725fe-6829-11e8-9898-158bd0c66e00.png">

**Comment by tennist** [comment]
I just created a pull request that fixes this issue so hopefully a new version of the plugin will be released shortly.

**Comment by tennist** [comment]
Issue now resolved so closing

**Comment by tangtermsak** [comment]
I use trick by set overlap:true 

  admob.banner.config({
    id: admobid.banner,
    isTesting: false,
    autoShow: true,
    **overlap:true,**
  })

then I add style padding-bottom:50px; to the page in my case I add to body,html and my ads display at bottom

**Comment by mayankkataria** [comment]
I'm still facing this issue on android.
