### ISSUE TITLE
Interstitials automatically show by default

### ISSUE THREAD

**Issue by arsis-dev** [ratson/cordova-plugin-admob-free#236]
Using
```
admob.interstitial.config({
     id: 'ca-app-pub-3940256099942544/1033173712'
});
```
my interstitial ads display automatically after they're loaded (contrary to the documentation), but when I add `autoShow: false` they no longer display automatically.

The documentation says default value for autoShow is false.

**Comment by ratson** [comment]
Close as docs updated.
