### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sirchacal** [ratson/cordova-plugin-admob-free#24]
hey ratson , 
I'm not a javascript programmer , I'm not able to make it work , in a cordova project, can you explain me how to integrate this code I already install the cordova plugin ..

[index.txt](https://github.com/ratson/cordova-plugin-admob-free/files/573711/index.txt)

this is the index.js

**Comment by ratson** [comment]
@sirchacal Here is the [example code](https://github.com/ratson/cordova-plugin-admob-free/blob/master/example/www/js/index.js). Feel free to reopen this issue if you have any difficulties to run it.
