### ISSUE TITLE
Where can I change the PLAY_SERVICES_VERSION?

### ISSUE THREAD

**Issue by merbin2012** [ratson/cordova-plugin-admob-free#241]
@ratson where can I found the following line as per your documentation, I am searching in all config.xml files but I can not able to find it.

Customize Google Play Services versions (Android only)
The default PLAY_SERVICES_VERSION is set to 11.0.4. If you need a different version, edit config.xml with following,

```
<plugin name="cordova-admob-sdk" spec="~0.13.1">
    <variable name="PLAY_SERVICES_VERSION" value="11.6.0" />
</plugin>
```

**Comment by lolaswift** [comment]
I guess you should just add those lines. Check the cordova-admob-sdk version first.

**Comment by srikanth-wgl** [comment]
You can add it anywhere in config.xml file. Just add it before the closing `</widget>` tag. It will work.

**Comment by Danitrebu** [comment]
It took the whole day to find the answer for me. Just go for project.properties and change the version

**Comment by Lenndev** [comment]
@Danitrebu  true that works, but is merely a manual solution. it is indeed the problem that cordova-admob-sdk sets the version to 11.0.4 so apparently installing that plugin with variable will solve this problem...

**Comment by rodrigograca31** [comment]
Setting it manually in config.xml or even doing what @Lenndev said didnt work for me.... it still complains about that variable...

**Comment by rodrigograca31** [comment]
solved it by setting it directly in `project.properties` in `platforms/android/`

**Comment by merbin2012** [comment]
All of your google framework must have the same version, so you can solve it by the following way

```
target...............
android.li.................
android.li..................
cordova.system.library.1=com.google.android.gms:play-services-analytics:+
cordova.gradle.include.1=cordova-plugin-firebase/Codeplay-build.gradle
cordova.system.library.2=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.3=com.google.firebase:firebase-core:+
cordova.system.library.4=com.google.firebase:firebase-messaging:+
cordova.system.library.5=com.google.firebase:firebase-config:+
cordova.system.library.6=com.google.firebase:firebase-perf:+
cordova.system.library.7=com.google.android.gms:play-services-base:+
cordova.system.library.8=com.google.android.gms:play-services-ads:+
```

**Note:**
**No need to all package name, just you need to replace your existing package name only**
