### ISSUE TITLE
version 0.17.1 having error when build 

### ISSUE THREAD

**Issue by havenht** [ratson/cordova-plugin-admob-free#244]
version 0.17.1 having error when build using adobe website

**Comment by ratson** [comment]
@havenht Would you provide more information? What is the error? What are the steps to recreate the error?

**Comment by vptcnt** [comment]
:compileReleaseJavaWithJavac
/Users/vincent/IonicCnt/KOMITID/platforms/android/src/name/ratson/cordova/admob/rewardvideo/RewardVideoListener.java:90: error: method does not override or implement a method from a supertype
    @Override
    ^

**Comment by JeanClaudeCottier** [comment]
It looks like we are loading an old admob sdk that doesn't support onRewardedVideoCompleted. If I comment this overloaded function, the project compile without any problems (but obviously I don't want tomiss close events so, that's not a solution).

**Comment by kenziy** [comment]
having the same issue do we have a solution on this?

**Comment by nilesh52** [comment]
Remove new version and install old version to resolve problem ,
ionic cordova plugin add cordova-plugin-admob-free@0.17.0

**Comment by JeanClaudeCottier** [comment]
I've posted an alternative solution here. I guess it is more future proof.
https://github.com/ratson/cordova-plugin-admob-free/issues/246

**Comment by kenziy** [comment]
Yeah @nilesh52 it seems installing the old version is a good idea for now

**Comment by gostrafx** [comment]
@nilesh52 
it's working now 💯
thank you so much 👍
