### ISSUE TITLE
Black screen on iOS

### ISSUE THREAD

**Issue by code4youreal** [ratson/cordova-plugin-admob-free#25]
Hi! 

The Apple Support Recejted my app because got black screen on iOS 10.11, so something not working good here. Can you check, because I got black screen on Android too. Thank you!

**Comment by vintage** [comment]
Duplicate: https://github.com/ratson/cordova-plugin-admob-free/issues/23

**Comment by ratson** [comment]
@vintage Thank you. I have invited you to be a collaborator, so you could help closing issues in the future.
