### ISSUE TITLE
Fail to compile Android project. Unnecessary @Override at line 90 in RewardVideoListener.java

### ISSUE THREAD

**Issue by santi-cognifit** [ratson/cordova-plugin-admob-free#251]
This is a sample from my console's output:
```
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:app:processReleaseResources
:app:generateReleaseSources
:app:javaPreCompileRelease
:app:compileReleaseJavaWithJavac/Users/cognifit/Workspace/cognifitSocialJS/platforms/android/app/src/main/java/name/ratson/cordova/admob/rewardvideo/RewardVideoListener.java:90: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

FAILURE: Build failed with an exception.
```

Removing [this line](https://github.com/ratson/cordova-plugin-admob-free/blob/748ad0cfb6b6b255411edbc9c6bc13c16f07b7cc/src/android/rewardvideo/RewardVideoListener.java#L90) just fix it

**Comment by stionic** [comment]
Hi,

Thank for your information.
This line come from #234 
But no idea why it make problems?

Regards.

**Comment by srikanth-wgl** [comment]
The callback method `onRewardedVideoCompleted()` has been added in Google Mobile Ads SDK version 12.0.0 for Android. We can check it in the release notes [here](https://developers.google.com/admob/android/rel-notes).

The `@Override` annotation will ensure that the callback is implemented in `RewardedVideoAdListener` implementation. It raises error with SDK versions below 12.0.0 as there is no such callback there.

Removing that `@Override` annotation will fix the issue for older SDK versions without causing any problems in newer versions. Reverting #234 will fix the issue.

**Comment by stionic** [comment]
Hi,

Nice info, but it still error if set play-services-ads to latest (previous version 0.17.0 work fine):

> dependencies {
>     implementation fileTree(dir: 'libs', include: '*.jar')
>     // SUB-PROJECT DEPENDENCIES START
>     implementation(project(path: "CordovaLib"))
>     compile "com.google.android.gms:play-services-ads:+"
>     compile "com.android.support:support-v4:26.+"
>     compile "com.google.android.gms:play-services-base:+"
>     // SUB-PROJECT DEPENDENCIES END
> }
> 

Do you have any suggest?

Regards.

**Comment by santi-cognifit** [comment]
In my case I am using 11.+ version due to some other plugin incompatibility (firebase I suppose):
```
 compile "com.google.android.gms:play-services-base:11.+"
 compile "com.google.android.gms:play-services-ads:11.+"
```

I am not very good at JAVA, and not really sure if this exists, but if we could set `@Override` to be optional (overloading the method) it would fix the problem and maintain compatibility with older google SDKs

**Comment by shagun121** [comment]
i have fixed this issue. just follow my steps.
go to platforms/src/android/app/src/main/java/name/ratson/cordova/admob/rewardvideo/RewardVideoListener.java

AND GO TO LINE NO 90 AND REMOVE @override and everything will work fine.
