### ISSUE TITLE
[iOS] does not work alongside cordova-plugin-statusbar

### ISSUE THREAD

**Issue by hoboman313** [ratson/cordova-plugin-admob-free#260]
Interstitial ads cause the app body to get vertically mis-aligned after being shown ONLY when the cordova-plugin-statusbar is also installed. In other words, the page content starts to overflow past the banner. Some have suggested to call ```admob.banner.show()``` (this does solve the problem when called manually) in the handler of the "interstrial close event", but this event not seem to get called anymore in iOS (tested with 11.4).

**Comment by ratson** [comment]
@hoboman313 Would you setup a example repo showing the problem?

**Comment by hoboman313** [comment]
I would like not to unless you're unable to repro the issue. Note that this is a dup of #107 from last Sept. which went unresolved but its first workaround of listening on "admob.interstitial.events.CLOSE" no longer works as that event is no longer triggered when closing an interstitial on iOS. I had to go with the second suggested workaround of removing "cordova-plugin-statusbar" which worked but is kinda sucky.

My env is: 
cordova-cli: 7.0.0
cordova-plugin-admob-free: ^0.17.2,
cordova-ios: ^4.5.4,
cordova-plugin-wkwebview-engine: ^1.1.4

**Comment by hoboman313** [comment]
The CLOSE callback workaround works well if the next interstitial does not get prepared when one is already being shown. Additional comments and fixes on the issue are in the comments of #232 
Closing.

**Comment by tennist** [comment]
@hoboman313 I added the line of code to resize the view after closing an interstitial in my PR #262
