### ISSUE TITLE
iPhone X banner at the top shows behind the statusbar

### ISSUE THREAD

**Issue by altick** [ratson/cordova-plugin-admob-free#261]
Hey Guys,
I ran into an issue with displaying the ads at the top of the iPhone X. The banner does display but it appears behind the status bar even despite setting the option
`offsetTopBar: true`

I also tried to configure the status bar to not overlay the web view:
`this.statusBar.overlaysWebView(false);`
but on iPhoneX it seems to have no effect.

This is what I get:
![iphone x capture](https://user-images.githubusercontent.com/7649102/42408118-d6d85edc-81c7-11e8-8940-1a3c185bb9cf.JPG)

Otherwise it works great on any other iOS device.

Is there anything I've been missing?

Versions I'm using:

**Cordova**
```
cordova (Cordova CLI) : 8.0.0
Cordova Platforms  : ios 4.5.4
```

**config.xml**
`<plugin name="cordova-plugin-admob-free" spec="^0.17.2" />`

**package.json**
`"@ionic-native/admob-free": "4.9.0"`

Many thanks!

**Comment by AlanCrevon** [comment]
Hi.

Same problem here with an iPhone 6s : 

![img_4401](https://user-images.githubusercontent.com/5858108/42423689-d90d3f3c-82fe-11e8-9470-046f12126d77.jpg)

Same config as @altick 's except

**package.json**
`"@ionic-native/admob-free": "4.7.0"`

Do we miss something in the documentation ?

Cheers,
Alan

**Comment by hoboman313** [comment]
Try removing the cordova statusbar plugin? Fixed a similar issue for me.

**Comment by AlanCrevon** [comment]
@hoboman313 : i saw this trick on another issue. Didn't save the problem for me so i reinstalled the plugin. Thanks anyway. :)

**Comment by hoboman313** [comment]
In that case you probably need:
```
body {
  padding-top: constant(safe-area-inset-top);
  padding-top: env(safe-area-inset-top);
}
```

**Comment by tennist** [comment]
@altick & @AlanCrevon will you guys verify that my PR #262 fixes this issue for you.

**Comment by altick** [comment]
@tennist your fix is working nicely, great job! Even together with the status bar plugin which is necessary to set the statusbar's content to the light style otherwise there is nothing visible on the status bar.

Looking good:
![iphone x capture fixed](https://user-images.githubusercontent.com/7649102/42682867-067dfc82-868c-11e8-804a-0cb553850e16.JPG)

**Comment by ratson** [comment]
Close by https://github.com/ratson/cordova-plugin-admob-free/pull/262
