### ISSUE TITLE
Banner not showing up

### ISSUE THREAD

**Issue by oangelo** [ratson/cordova-plugin-admob-free#27]
I have noticed a strange behavior in Android.
I can make the banner to show up when doing this
```
 AdMob.createBannerView({
    autoShow: true,
  });
```
But this will also make Interstitial to "auto show", I think this is unappropriated, since I have set before:
```
  AdMob.prepareInterstitial({
    adId: admobid.interstitial,
    autoShow: false,
  })
```
this means that autoShow is global, and I think it should not.

The main problem is that the banner does not shows up when I call:
```
// Create banner
AdMob.createBannerView();

// Show the banner
AdMob.showAd(true);
```
A very ugly workaround is to
```
AdMob.createBannerView({autoShow: true,});
AdMob.prepareInterstitial({autoShow: false,})
```
Am I missing something? By the way, I am using crosswalk.

**Comment by bflopez** [comment]
Weird that it doesn't show with
    AdMob.createBannerView();

It should show.

**Comment by oangelo** [comment]
I realized that because the example uses this:
https://github.com/ratson/cordova-plugin-admob-free/blob/6b2f1298f2c9ee68f771f5c6188003a48bb6ec04/example/www/js/index.js#L19-L21
And I was not able to show the banner otherwise.

Another strange thing is that the README.mk says this:
```
autoShow: false,  // auto show interstitial ad when loaded
```
That suggests that "autoShow" is only for interstitial and not for banner, but, clearly is not.

**Comment by ratson** [comment]
@oangelo v0.5.0 should address this issue.
Feel free to reopen if you still have problem.
