### ISSUE TITLE
 With version v0.4.0 in IOS 7.0 it fails. With v0.3.1 works

### ISSUE THREAD

**Issue by warcry2000** [ratson/cordova-plugin-admob-free#28]
Using version IOS 7.0 with v0.4.0 it fails, with v0.3.1. works.

The problem is that in addition the 'deviceready' event does not fire.
This problem does not execute the rest of code.

Does anyone know what can happen? Thanks

**Comment by vintage** [comment]
What version of cordova and cordova-ios are you using? Try the latest one `cordova@6.4.0` and `cordova-ios@4.3.0`.

**Comment by warcry2000** [comment]
Hello,
I tried with cordova@6.4.0 and cordova-ios@4.3.0 and it failed, then with the previous ones and it also failed.
Later, just for testing, I tried with cordova-admob-pro that has the same ios framework, and with this if the event 'deviceready' was launched,

Version v0.3.1. It works well.

**Comment by vintage** [comment]
That's a strange behavior, I'm currently using this plugin for serving ads in few games and it works correctly on both - Android & iOS.

You should try to run basic example and see if the deviceready is called - https://github.com/ratson/cordova-plugin-admob-free/tree/master/example

**Comment by warcry2000** [comment]
In IOS higher than 7 it works, and in android too. But in the IOS 7 that I have it does not go.
Thank you very much, then I prove that I do not have my cell phone here.

**Comment by warcry2000** [comment]
Hi @vintage , I was testing with the simple example, and I found the error. The error occurs because the AdMob.js file contains two lines repeated on lines 9 and 14: LARGE_BANNER: 'LARGE_BANNER'
This makes in older browsers cut all the javascript, and for that reason does not skip the 'deviceready', so it will fail on some phones.

**Comment by vintage** [comment]
@warcry2000 Bingo, you are totally right! Can you make a PR or want someone else to do it for you? Additionally does it solves the issue and ads are working properly?

**Comment by warcry2000** [comment]
@vintage  Yes, everything works correctly by removing one of the two lines, I have to do some things urgently, so when I finish them I can create the PR. Although if you want to advance and create it earlier, I would appreciate it.

**Comment by warcry2000** [comment]
@vintage I just realized it, greetings
