### ISSUE TITLE
Not working with play-services-ads v17.0.0

### ISSUE THREAD

**Issue by paulstelzer** [ratson/cordova-plugin-admob-free#286]
Google published version 17 of play-services-ads. To make it working with it, the plugin has to add a new requirement for a `<meta-data>` tag in AndroidManifest.xml:

`Google AdMob publishers are required to specify a <meta-data> tag with key com.google.android.gms.ads.APPLICATION_ID. See the AdMob getting started guide for more details.`

Source: https://developers.google.com/android/guides/releases#october_5th_2018

**Comment by schnouz** [comment]
Try adding this in your config.xml
```
<config-file parent="./application" target="AndroidManifest.xml">
        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="yourApplicationId" /></config-file>
```

**Comment by paulstelzer** [comment]
@schnouz Yes, I know :D I only opened this issue for my PR ;)

**Comment by schnouz** [comment]
@paulstelzer ahah my bad :)
