### ISSUE TITLE
index.js:177 Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by DooDiddle** [ratson/cordova-plugin-admob-free#292]
After installing admob-free plugin, my app stops working. This is for android and ionic4, with capacitor installed. The error I see says:

index.js:177 Uncaught TypeError: Object(...) is not a function
    at index.js:177
    at Object../node_modules/@ionic-native/admob-free/index.js (index.js:186)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.component.ts:11)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)
(anonymous) @ index.js:177
./node_modules/@ionic-native/admob-free/index.js @ index.js:186
__webpack_require__ @ bootstrap:81
./src/app/app.module.ts @ app.component.ts:11
__webpack_require__ @ bootstrap:81
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:81
0 @ main.ts:12
__webpack_require__ @ bootstrap:81
checkDeferredModules @ bootstrap:43
webpackJsonpCallback @ bootstrap:30
(anonymous) @ main.js:1
content_script.js:10 Uncaught Error: Unrecognized event name: undefined
    at receivePageEvent (content_script.js:10)
    at content_script.js:4

____

Here is how I installed admob:

npm install cordova-plugin-admob-free
npm install @ionic-native/admob-free
npx cap update

in package.json I see
"@ionic-native/admob-free": "^4.15.0",
"cordova-admob-sdk": "^0.20.0",

In app.module.ts
import { AdMobFree } from '@ionic-native/admob-free'; 
...
  providers: [
    StatusBar,
    SplashScreen,
    AdMobFree,

Can anyone help with this problem?

**Comment by DooDiddle** [comment]
Here is index.js line 177:

AdMobFree = __decorate([
    Plugin({
        pluginName: 'AdMobFree',
        plugin: 'cordova-plugin-admob-free',
        pluginRef: 'admob',
        repo: 'https://github.com/ratson/cordova-plugin-admob-free',
        platforms: ['Android', 'iOS']
    })
], AdMobFree);
return AdMobFree;

**Comment by DooDiddle** [comment]
To test the app on android phone via usb I did:
 ionic cordova run android
which gave error:  Could not install from "android" as it does not contain a package.json file.
How can I test the app on my phone to see that admob plugin is working?

**Comment by Rinlama** [comment]
I am having the same issue.

**Comment by FrnandMG** [comment]
Same here.
