### ISSUE TITLE
Inatll plugin : Error: Variable(s) missing: ADMOB_APP_ID

### ISSUE THREAD

**Issue by tzecat** [ratson/cordova-plugin-admob-free#295]
Trying to install the plugin:
#cordova plugin add cordova-plugin-admob-free
 
Fail with error below:
Installing "cordova-plugin-admob-free" for android
Failed to install 'cordova-plugin-admob-free': Error: Variable(s) missing: ADMOB_APP_ID

What's wrong, does anybody already goy this error ?

**Comment by ratson** [comment]
See updated https://github.com/ratson/cordova-plugin-admob-free#installation

**Comment by rafaellop** [comment]
@ratson It seems that the `AndroidManifest.xml` is not properly modifed upon building. No `meta-data` is added regarding the `ADMOB_APP_ID` to the manifest file.
