### ISSUE TITLE
only test ads are shown

### ISSUE THREAD

**Issue by jony89** [ratson/cordova-plugin-admob-free#297]
Test ads are shown perfectally,

When I build with release, for a live ads. no ads are shown and I get 

> Internal error

In the `LOAD_FAIL` event. 

I've also tried adding the variable ADMOB_APP_ID accodring to the new docs, but still, same issue.

@ratson

**Comment by jony89** [comment]
some of my users do get the ads. yet I don't. 
It might have any connection to the android version? (they are not shown in v9.0.0)

**Comment by lfreneda** [comment]
@jony89 how did you solve it?

**Comment by jony89** [comment]
It was a matter of time.

**Comment by Mathewkutty** [comment]
How long will it take to show ad?
