### ISSUE TITLE
Google started to require us to put APPLICATION_ID in AndroidManifest.xml from 05/10/2018

### ISSUE THREAD

**Issue by gatang007** [ratson/cordova-plugin-admob-free#299]
Hi, just found out that Google put a new requirement for using the Admob on 5/10/2018. Failed to do so would not be able to start the app.

I got the following error when I started the app on the real device. The App crashed right away while it started.

10-12 05:03:40.008 10510 10510 E AndroidRuntime: ******************************************************************************
The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    
should follow the instructions here: https://goo.gl/fQ2neu to add a valid  
App ID inside the AndroidManifest. Google Ad Manager publishers should 
follow instructions here: https://goo.gl/h17b6x.                           
******************************************************************************

Reference link:
https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml

I tried to follow the instruction by putting the Application Id and the Admob Id to my AndroidManifest.xml. But it didnt help. Is there any way we could get around of this with the current version of Admob plugin?

Would the upcoming cordova-plugin-admob-free support this requirement?

**Comment by gatang007** [comment]
This has been addressed. Thanks very much.
 https://github.com/ratson/cordova-plugin-admob-free#installation

**Comment by edento** [comment]
> This has been addressed. Thanks very much.
> https://github.com/ratson/cordova-plugin-admob-free#installation

If the app should work on both iOS and android, should I install with android ID for both platforms? what should i do with iOS later? change manually?
