### ISSUE TITLE
Family friendly and age appropriate ad filtering (for iOS)

### ISSUE THREAD

**Issue by hypersurge** [ratson/cordova-plugin-admob-free#3]
@ratson thank you for this plugin.

I can see settings within "wp8" and "android" plugins for age appropriate settings ("birthday" and "forChild" / "forFamily" respectively).  However I can't find similar options within the iOS plugin.

Is this by design or outside of the scope of this Admob plugin for iOS?  Might it be possible to include the same options across all plugins in a consistent way?

**Comment by ratson** [comment]
I am not sure if iOS has the equivalent feature.

It should be safe to pass those options, which will just be ignored for iOS.

**Comment by hypersurge** [comment]
There is some reference here to age appropriate options (classified under iOS):
https://firebase.google.com/docs/admob/ios/targeting

**Comment by ratson** [comment]
@hypersurge Thanks for the reference, will take a look this weekend.

Feel free to send pull request if you would like to fix it, I will review that as soon as I can.

**Comment by ratson** [comment]
Done
