### ISSUE TITLE
can't install. Failed to install 'cordova-plugin-admob-free': Error: Variable(s) missing: ADMOB_APP_ID

### ISSUE THREAD

**Issue by moomdate** [ratson/cordova-plugin-admob-free#300]
## i can't install this plugin. problem report below

Installing "cordova-plugin-admob-free" for android
Failed to install 'cordova-plugin-admob-free': Error: Variable(s) missing: ADMOB_APP_ID
    at Object.mergeVariables (\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\variable-merge.js:58:15)
    at \npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:315:44
    at _fulfilled (\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)

when i use 

> $ ionic cordova plugin remove cordova-plugin-admob-free

error report same problem
(node:5968) UnhandledPromiseRejectionWarning: Error: Variable(s) missing: ADMOB_APP_ID

==============================
ionic (Ionic CLI)  : 4.2.1
Ionic Framework    : ionic-angular 3.9.2
@ionic/app-scripts : 3.2.0
------------------------------------------------
cordova (Cordova CLI) : 8.0.0
Cordova Platforms     : android 7.0.0
------------------------------------------------
Android SDK Tools : 26.1.1
NodeJS            : v8.12.0
npm               : 6.4.1
OS                : Windows 10
==============================

**Comment by jony89** [comment]
See new docs,

You must run : 

``
cordova plugin add cordova-plugin-admob-free --save --variable ADMOB_APP_ID="<YOUR_ADMOB_APP_ID_AS_FOUND_IN_ADMOB>"
``

**Comment by moomdate** [comment]
ok thank you bro.

**Comment by rafaellop** [comment]
RTFM
