### ISSUE TITLE
Ads keeps showing test

### ISSUE THREAD

**Issue by sysads** [ratson/cordova-plugin-admob-free#31]
I have just sorted out why ads keeps showing test after adding my admob IDs and removing the isTesting line. Now the new problem is it appears ads show but not working.

For instance, there are some ads that plays a video, when this shows, the timer stays stuck. its like its displaing a png file rather than rendering a video.

Any help?

**Comment by ratson** [comment]
@sysads Would you clone the example, change the publisher IDs, remove `isTesting` option in the example, run and see if your problem still happen?
I am not sure what had been going wrong.

**Comment by sysads** [comment]
Thanks for the reply. I didn't bother to proceed with this so had to improvice by exporting project to Mobile web and using cordova to inject admob into it and all good.
