### ISSUE TITLE
Phonegap Build Error: Variable(s) missing: ADMOB_APP_ID

### ISSUE THREAD

**Issue by mujaffars** [ratson/cordova-plugin-admob-free#310]
Facing Error: Variable(s) missing: ADMOB_APP_ID issue

I am creating apk with the help of web interface phonegap build https://build.phonegap.com

How should I add admob_app_id in the config.xml file

Is it possible?

**Comment by Akhouad** [comment]
re-install the plugin with this command:

`cordova plugin add cordova-plugin-admob-free --save --variable ADMOB_APP_ID="<YOUR_ADMOB_APP_ID_AS_FOUND_IN_ADMOB>"`

**Comment by mm44** [comment]
`<plugin name="cordova-plugin-admob-free">
    <variable name="ADMOB_APP_ID" value="ca-app-pub-3940256099942544~3347511713" />
</plugin>`

**Comment by mujaffars** [comment]
Thank you @mm44 it worked
