### ISSUE TITLE
Admob Banned Invalid Activity

### ISSUE THREAD

**Issue by wahidung** [ratson/cordova-plugin-admob-free#319]
Why, I use this Admob plugin, my Admob / Adsense account has been banned for reasons of Invalid Activity, even though I play honestly.

**Comment by ratson** [comment]
You should contact Google for the reasons, no one here can answer for your particular case. It is unlikely relate to this plugin as many using it without problem. Although this should not be necessary  You may try rewrite to use `cordova-admob-plus` to see if it helps.

**Comment by wahidung** [comment]
@ratsonI have already tried admob-plus but the error, I have already written in issues admob plus but there is no solution. [https://github.com/admob-plus/admob-plus/issues/25](url)
