### ISSUE TITLE
Is there any possibility of using “Child-directed setting” using this plugin?

### ISSUE THREAD

**Issue by Venkat-TTapp** [ratson/cordova-plugin-admob-free#32]
This is a question, not an issue. Not sure where to raise this question for this plugin, so I have raised this question under issues, sorry if this is not appropriate.

Can we use “Child-directed-setting” For purposes of the Children's Online Privacy Protection Act (COPPA), there is a setting called tagForChildDirectedTreatment in admob which needs to be flagged to receive COPPA complaint ads.

More information on this link:
https://firebase.google.com/docs/admob/ios/targeting#child-directed_setting

Please let me know if we can tag for child directed treatment using this plugin.

Regards,
Venkat

**Comment by ratson** [comment]
In fact, I have added the support Android.
As I don't have time to add support for iOS, so I am not adding documentation about it.

Does Android support is sufficient for you?
If so, I would document it.
For iOS support, I really need some helping hands.

**Comment by Venkat-TTapp** [comment]
Hi Ratson,

Thanks for your reply.

It would be great if feature was available for iOS, 

I would try this for Android ( currently none of my app are released in US due to COPPA restrictions), please let me know how to do this.

Regarding support for iOS: Sorry I do not have technical knowledge to help on this, I can help you to documenting clear steps which can be helpful for users.

**Comment by ratson** [comment]
@Venkat-TTapp I have documented the options in https://ratson.github.io/cordova-plugin-admob-free/function/index.html#static-function-setOptions
`options.forChild` and `options.forFamily` should be what you need.

**Comment by Venkat-TTapp** [comment]
Thanks for your prompt response Ratson. I sincerely appreciate your time and effort for my query.

**Comment by ratson** [comment]
v0.5.0 is out with the support for both Android and iOS.
Let me know if it works for you.
