### ISSUE TITLE
Very many error reports when in production

### ISSUE THREAD

**Issue by oangelo** [ratson/cordova-plugin-admob-free#33]
I was trying to use this plugin, because it is free and has no ad share. I am using ionic, I had a hard time trying to make it work, but I am able to run it using Crosswalk.  I am using Google Analytics to log when an ad is receved, shown or retruns an error, because AdMob was not logging the amout of impressions I would expect. While it does works in my phone flaweslessly, when in production, it logs a lot of errors. Using  cordova-plugin-admob-simple also gives me many many erros also, but I got no error when using cordova-admob-pro. However, cordova-admob-pro is evil, it has remote control and ad share. Anybody is logging data in Analytics and experiencing the same resutls? I tried to look the code, but my Java and Android skills are not very good, I can only make some tests... :-(

**Comment by becvert** [comment]
Hi @oangelo 
could you give us details of the errors that are reported?
Thank you

**Comment by ratson** [comment]
I wish I have more time to improve this plugin, but supporting features which I don't use is hard and time consuming.

Good to hear that you are willing help on testing, most issues does not include clear steps how a problem occurs, some are more difficult as they (looks) happen randomly.

I will look into some issues this weekend, but could not guarantee anything.

**Comment by oangelo** [comment]
Hi @becvert 

As I said, I can't reproduce the problem in my own phone when testing, I think it is an intermittent problem, because I only noticed it when the app is in production. I did not logged the problem description, only how many times it happened. I am not an expert in this field... But I am now using  https://github.com/floatinghotpot/cordova-admob-pro and no error is been logged.

I had the same problem when using sunnycupertino/cordova-plugin-admob-simple, see:
https://github.com/sunnycupertino/cordova-plugin-admob-simple/issues/13. But he had no idea of what it could be.

The code I was using is this:
```
var adReady = false;
var adTimer = true;
var adPluginLoaded = false;
var adBannerShown = false;
var lastCardName = 'none';

function initAd(){
  if ( window.plugins && window.plugins.AdMob ) {
    adPluginLoaded = true;
    var ad_units = {
      ios : {
        banner: '*****',       //PUT ADMOB ADCODE HERE
        interstitial: '*****'  //PUT ADMOB ADCODE HERE
      },
      android : {
        banner: '*****',       //PUT ADMOB ADCODE HERE
        interstitial: '*****'  //PUT ADMOB ADCODE HERE
      }
    };
    var admobid = ( /(android)/i.test(navigator.userAgent) ) ? ad_units.android : ad_units.ios;

    window.plugins.AdMob.setOptions( {
      publisherId: admobid.banner,
      interstitialAdId: admobid.interstitial,
      adSize: window.plugins.AdMob.AD_SIZE.LARGE_BANNER,  //use SMART_BANNER, BANNER, IAB_MRECT, IAB_BANNER, IAB_LEADERBOARD
      bannerAtTop: false, // set to true, to put banner at top
      overlap: false, // banner will overlap webview 
      offsetTopBar: false, // set to true to avoid ios7 status bar overlap
      isTesting: false, // receiving test ad
      autoShow: false // auto show interstitial ad when loaded
    });

    
    registerAdEvents();
    window.plugins.AdMob.createInterstitialView();  //get the interstitials ready to be shown
    window.plugins.AdMob.requestInterstitialAd();

  } else {
    //alert( 'admob plugin not ready' );
  }
}
//functions to allow you to know when ads are shown, etc.
function registerAdEvents() {
  document.addEventListener('onReceiveAd', function(){});
  document.addEventListener('onFailedToReceiveAd', function(data){
    //alert("fail to receive");
    setTimeout( function() {
      window.plugins.AdMob.createInterstitialView();          //REMOVE THESE 2 LINES IF USING AUTOSHOW
      window.plugins.AdMob.requestInterstitialAd();
    }, 1000*30);
    window.analytics.trackEvent('Ad', 'Interstetial', "Error");
  });
  document.addEventListener('onPresentAd', function(){});
  document.addEventListener('onDismissAd', function(){ });
  document.addEventListener('onLeaveToAd', function(){ });
  document.addEventListener('onReceiveInterstitialAd', function(){
    //alert("inter receive");
    adReady = true;
    window.analytics.trackEvent('Ad', 'Interstetial', "Received");
  });
  document.addEventListener('onPresentInterstitialAd', function(){ });
  document.addEventListener('onDismissInterstitialAd', function(){
    //alert("inter dimiss");
    window.plugins.AdMob.createInterstitialView();          //REMOVE THESE 2 LINES IF USING AUTOSHOW
    window.plugins.AdMob.requestInterstitialAd();           //get the next one ready only after the current one is closed
    adReady = false;
    window.analytics.trackEvent('Ad', 'Interstetial', "Closed");
  });
}

//display the banner
function showBannerFunc(){
  //alert('show banner');
  if (adPluginLoaded && !adBannerShown){
    window.plugins.AdMob.createBannerView({autoShow: true,});
    window.plugins.AdMob.prepareInterstitial({autoShow: false,})
    adBannerShown = true;
  }
}

//display the interstitial
function showInterstitialFunc(){
  if (adPluginLoaded){
    if (adReady && adTimer){
      setTimeout( function() {
        adTimer = true;
      }, 1000*60);
      adTimer = false;
      window.plugins.AdMob.showInterstitialAd();
      window.analytics.trackEvent('Ad', 'Interstetial', "Show");
    }
  }
}

function closeBannerFunc(){
  if (adBannerShown && adPluginLoaded){
    window.plugins.AdMob.destroyBannerView();
    adBannerShown = false;
  }
}
```
And this is what I got on a typical day:
![image](https://cloud.githubusercontent.com/assets/1669411/20852273/23378aa8-b8cc-11e6-8d04-2096a0adb352.png)

Hope this helps

**Comment by becvert** [comment]
You're calling prepareInterstial in showBannerFunc. Is that normal?
Maybe it is. Maybe it does not matter. I'm just trying to understand the code.

**Comment by oangelo** [comment]
@becvert, take a look at #27. There is explained why I am doing this.

**Comment by ratson** [comment]
As v0.6 is out, I am closing this. Feel free to reopen if the problem still exists.
