### ISSUE TITLE
My App Rejected: Interstitial ads that appear after the user has exited the app

### ISSUE THREAD

**Issue by ipsjolly** [ratson/cordova-plugin-admob-free#340]
My android application is rejected due to the following issue:

**Issue: Violation of Interfering with Apps, Third-party Ads, or Device Functionality policy
--
Ads should not be shown in a way that results in inadvertent clicks.For example, we don’t allow:Interstitial ads that appear after the user has exited the app**

The Code I used in App

  showInterstitialAds() {
    let interstitialConfig: AdMobFreeInterstitialConfig = {
      isTesting: true, // Remove in production
      autoShow: true//,
      //id: "ca-app-pub-3940256099942544/6000000001"
    };
    this.admobFree.interstitial.config(interstitialConfig);
    this.admobFree.interstitial.prepare().then(() => {
    }).catch(e => alert(e));
  }

How can i use prepair, isReady and show method if autoShow set to false?

UPDATED Feb 19 : I have resolved this issue ans explained method in this post https://www.freakyjolly.com/resolve-interstitial-ads-that-appear-after-the-user-has-exited-the-app-issue-in-ionic-3-application/

**Comment by IghodaloEllis** [comment]
Im having same issue
however still trying to implement this:

`@Override
public void onDestroy()
{
    super.onDestroy();
    if (mInterstitialAd != null) {
        mInterstitialAd.destroy();
    }
}`
