### ISSUE TITLE
Works fine with DEVAPP testing, does not works when installing .apk on a real device

### ISSUE THREAD

**Issue by satyam-dev** [ratson/cordova-plugin-admob-free#342]
I am trying to use this plugin. Everything seems to work fine when using the devsapp for testing. But when building apk and installing it on device, it does not shows the ads.

**Comment by Winamp9** [comment]
happened?

**Comment by satyam-dev** [comment]
Resolved! I don't get it why DEVAPP shows the the real ads when one can only show test ads on a real device before publishing an ad? I wasted around 1 complete week just trying to figure out whats wrong with my implementation because I was seeing real ads on DEVAPP and no ads at all on my real device.

**MAKE A NOTE ANYONE READING THIS THREAD** One can only show TEST ADS before publishing an app. BUT anyway DEVAPP shows the real ads.

So, `isTesting: true` AND commenting out the `id: <your ad id>` will only show the ads on a REAL DEVICE.
