### ISSUE TITLE
NO AD-SHARING? REALY? 

### ISSUE THREAD

**Issue by noveweb** [ratson/cordova-plugin-admob-free#350]
I have an app for raffles and my users bought 154 tickets yesterday all day. I set up my application to show 1 INSTERSTICIAL on every 1 sold ticket. In Google report shows only 32 impressions and 0 clicks !!! Where are the remaining 122 impressions and all my clicks ???

**Comment by srikanth-wgl** [comment]
There is no ad-sharing in this plugin. You can read the source code if you have any doubts about it.

Coming to your impressions issue your app might have sent 154 ad requests to AdMob server. But that does not mean AdMob served your app 154 ads. AdMob chooses ads to send to users based different factors like user's location, gender, interests, etc.. If it can't find suitable ad at that particular time it will not send any ad back to your app. It is called 'no-fill' response.

Check your AdMob reports to find how many network requests have been made from your app. And I don't expect any clicks for just 32 impressions. Users won't click on ads unless they are really curious about what is advertised on their screen.

**Comment by ratson** [comment]
I have added https://admob-plus.github.io/docs/faq.html#why-google-report-shows-less-impressions-than-the-number-of-ad-request-calls

@srikanth-wgl Thank you.

@noveweb Are you sure the ad is shown? Did you track the request calls? What is your match rate on AdMob report?

**Comment by rodrigograca31** [comment]
@ratson please close this issue.... he clearly doesn't know how ads work.
if he knew what he was talking about he would know that there's a diference bettwen `requests`, `requests matched`, `impressions`, etc and expect at most 1 or 2 clicks in about 150 impressions....

**Comment by noveweb** [comment]
@rodrigograca31 Quem foi que lhe perguntou alguma coisa, paspalho? Subestimar seja lá quem for ou o que quer que seja é o primeiro passo para se meter em situações indesejadas. Tenho 18 anos de mercado e não vou nem perder tempo discutindo com um moleque como você. Estou falando em bom português para que você entenda. Vou fechar a questão pelo simples fato de não poder provar que há algo de errado. Mas minha empresa já está deixando de usar esse plugin e minha equipe já está trabalhando no desenvolvimento de um plugin próprio. Coincidentemente, após abrir a questão aqui nossos cliques aumentaram exponencialmente.
