### ISSUE TITLE
cordova-admob-pro ...... 

### ISSUE THREAD

**Issue by rodrigograca31** [ratson/cordova-plugin-admob-free#351]
Hey @ratson 
I was just advising someone to [not use cordova-admob-pro](https://stackoverflow.com/questions/55572915/cordova-admobpro-ads-not-showing-on-android-devices/55599799#55599799) and got reminded that the issues you link to are no longer available. 

So I knew I had copies of those issues from when he tried to hide his scheme... Had to search through old backups but I got issue #450, #544 and #470.

Was thinking that before I loose this files maybe would be good to upload them to the cloud and link them in this repo?

Thoughts? Thanks

**Comment by ratson** [comment]
@rodrigograca31 Thank you for the information.
Would you link the screenshots in https://github.com/ratson/cordova-plugin-admob-free/issues/354 for others to reference?

**Comment by rodrigograca31** [comment]
done, shall we close this issue? (I should have emailed you but u dont have a public email in your profile :joy: )
