### ISSUE TITLE
"AdMob is not defined"

### ISSUE THREAD

**Issue by Script47** [ratson/cordova-plugin-admob-free#36]
#I found this plugin and it suited me perfectly, no extra nonsense and very good usability. I got it working and the test ads showed, however for some reason now I keep getting *AdMob is not defined*. It happens when I run the function `showInterstitial();` which I created.

**JavaScript**

**The Initialization**

```javascript
function onReady() {
    AdMob.setOptions({
	publisherId: 'my-id-here',
	interstitialAdId: 'my-id-here',
	bannerAtTop: false,
	overlap: true,
	offsetTopBar: false,
	isTesting: true,
	autoShow: false
    });

    AdMob.prepareInterstitial();
}

document.addEventListener('app.Ready', onReady, false);
```

**The Function**

```javascript
function showInterstitial() {
    AdMob.prepareInterstitial({}, function () {
        AdMob.showInterstitial();
    });
}
```

I then tried,

```javascript
function showInterstitial() {
    window.navigator.plugins.AdMob.prepareInterstitial({}, function () {
        window.navigator.plugins.AdMob.showInterstitial();
    });
}
```

I have tried reinstalling the plugin fresh, but it still didn't work.

**Miscellaneous** 

**Software:** Intel XDK (3641)

**Cordova Version:** 6.2.0

**Comment by ratson** [comment]
I am not sure about Intel XDK, should the event be `deviceready`? Also why `window.navigator.plugins.AdMob` instead of `AdMob`?

**Comment by Script47** [comment]
I was using the ```deviceready``` event, the issue was that I hadn't included Cordova. Simple fix really,

```html
<script src="cordova.js"></script>
```

and it was all working.
