### ISSUE TITLE
Interstitial on Android

### ISSUE THREAD

**Issue by bx67212** [ratson/cordova-plugin-admob-free#360]
This morning my app crash on admob.interstitial.show();
I see debug and it seems due to com.google.android.ads.AdActivity:

Second failure launching com.google.android.gms.ad.adactivity 
android.os.transactiontoolargeexception data parcel size

**Comment by fnrol** [comment]
same issue with me on android 8

+

https://github.com/ratson/cordova-plugin-admob-free/issues/359

**Comment by andrelicoski** [comment]
I have the same problem

**Comment by bx67212** [comment]
It seems not due to plugin...
I think Google have some issues, now is ok

**Comment by hypesol** [comment]
I am facing the same issue. is there any other best plugin for AdMob?

**Comment by andrelicoski** [comment]
I solved my problem by changing..
----------------
window.plugins.AdMob.interstitial.prepare();
window.plugins.AdMob.interstitial.show();
----------------
for..
----------------
window.plugins.AdMob.interstitial.prepare();
document.addEventListener('admob.interstitial.events.LOAD', function(e) {
		window.plugins.AdMob.interstitial.show();
});
----------------
