### ISSUE TITLE
Applicaiton is not loading after adding admob code.

### ISSUE THREAD

**Issue by senakasjp** [ratson/cordova-plugin-admob-free#376]
Hi, I am trying to get admob working on a Cordova app, which is loading an external website.  I have installed the cordova-plugin-admob-free and added the following code to the index.js.  After adding, the build didn't give any issue in debug mode. But when i install apk on the device, it doesn't load the page and remaining on "Device is Ready" screen.

index.js is added below.

var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    onDeviceReady: function() {
        this.receivedEvent('deviceready');

        if (navigator.connection.type == Connection.NONE) {
      		navigator.notification.alert('Check your internet connection!');
    	} else {
      	window.location="http://www.xxxxxxxxxxxxx.com";
    	}

    },

    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        // Admob code
        if(AdMob) {
            AdMob.createBanner({ 
            adID: 'ca-app-pub-2275440647866479/xxxxxxxxxxx', //my APP ad ID number for banner
            position: AdMob.AD_POSITION.BOTTOM_CENTER,
            autoShow: true, 
            isTesting: false});
        }
        else {
            alert('No AdMob');
        }
        // Admob code

        console.log('Received Event: ' + id);
    }
};

app.initialize();

Also, no alerts as well!

**Comment by senakasjp** [comment]
I found another working code. Thanks!

**Comment by uokivan** [comment]
@senakasjp 
Hi senakasjp
Can you share your code , please

thank you very much

by Ivan
