### ISSUE TITLE
[RFC] Better events

### ISSUE THREAD

**Issue by ratson** [ratson/cordova-plugin-admob-free#38]
I am working on next release to provide better API usage, one area to fix the emitted events.
I would like to hear some feedback for the following proposals before proceed,

#### 1. Generic events between different ad-types. E.g. `AdLoaded`, `AdFailed` events with `adType` in the event data.

**Pros**
- Less event types
- Some generic handling function, only need to listen to one event type. E.g. log `AdFailed`

**Cons**
- Some ad-types may emit more or less events. E.g. `AdRewarded` is only used by rewarded video
- Some ad-types event data may contain extra information, which can be hard to consume as `adType` need to be checked.

#### 2. Each ad-type has its own set of events. E.g, `BannerLoaded`, `InterstitialFailed` events.

**Pros**
- No need to check `adType` in the handling function

**Cons**
- Increase the number of events

I prefer (2) as it is more explicit, what do you think? @becvert @vintage @code4youreal @warcry2000
Maybe you have better idea.

**Comment by vintage** [comment]
I've been working with both approaches "generic events" and "specified events". As you said the generic events have one advantage - you can listen just for one event and receive multiple types of events using single line of code. Even if that sounds great, it's almost useless as in all of my apps I've had to do a conditional statement to check what exactly came in and decide what to do with it. I'm for the second approach as it gives more granularity and would keep the code clean.

Honestly the solution which I liked the most is the one used by the Heyzap - https://github.com/Heyzap/heyzap-cordova/blob/master/docs/advanced.md which simply split all the events into "namespaces", so we would have something like:

- AdMob.Banner.Events.LOADED
- AdMob.Banner.Events.CLICKED
- AdMob.Interstitial.Events.FETCH_SUCCEED
- AdMob.Interstitial.Events.FETCH_FAILED

**Comment by warcry2000** [comment]
Hello,
Since the events were so different, and because there were only a few common ones, I separated the events for each one.
So if someone uses only banner, worry about the events of the banner, if someone uses only videos, then only worry about the events of the videos.

Also I think the code would be cleaner.

**Comment by ratson** [comment]
Awesome, I like the namespace idea, it could group the methods too.
e.g. `admob.banner.events.LOADED`, `admob.rewardvideo.show()`

**Comment by warcry2000** [comment]
I think it is a great idea.
