### ISSUE TITLE
rewardvideo not working

### ISSUE THREAD

**Issue by frozenxis** [ratson/cordova-plugin-admob-free#39]
Hi. First of all, GREAT JOB!

i am using ionic2 rc3 with this cordova plugin.
Managed to make the banners work, but the reward video doesn't show up.

this is my code

```
        document.addEventListener('onReceiveRewardVideoAd', function() {console.log("onReceiveRewardVideoAd");});
        document.addEventListener('onPresentRewardVideoAd', function() {console.log("onPresentRewardVideoAd");});
        document.addEventListener('onPresentStartedRewardVideoAd', function() {console.log("onPresentStartedRewardVideoAd");});
        document.addEventListener('onDismissRewardVideoAd', function() {console.log("onDismissRewardVideoAd");});
        document.addEventListener('onRewardedVideo', function(data) {console.log("onRewardedVideo");});   
      this.admobid = {};
      if ( /(android)/i.test(navigator.userAgent) ) {  // for android & amazon-fireos
        this.admobid = {
          banner: 'MYCODE',
          // interstitial: 'ca-app-pub-xxx/xxx',
          // rewardvideo: 'ca-app-pub-xxx/xxx',
        };
      } else {  // for ios
        this.admobid = {
          banner: 'MYCODE',
          // interstitial: 'ca-app-pub-xxx/xxx',
          rewardvideo: 'MYCODE',
        };
      }

    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.hide();
      Splashscreen.hide();

      if(AdMob) {
        AdMob.setOptions({
          publisherId: this.admobid.banner,
          // interstitialAdId: this.admobid.interstitial,
          rewardVideoId: this.admobid.rewardvideo,
          bannerAtTop: false,  // set to true, to put banner at top
          overlap: false,  // set to true, to allow banner overlap webview
          offsetTopBar: false,  // set to true to avoid ios7 status bar overlap
          isTesting: true,  // receiving test ad
          autoShow: true  // auto show interstitial ad when loaded
        });

        // Create banner
        AdMob.createBannerView();
        AdMob.showAd();

        AdMob.prepareRewardVideo();
        AdMob.showRewardVideo(); 
      }
```

**Comment by warcry2000** [comment]
Hello @frozenxis,

In order to use video you need to install in addition to this plugin another mediation plugin, which one have you used?

You have printed the error that it returns with 'onFailedToReceiveAd'?

**Comment by frozenxis** [comment]
hi, thanks for quick reply
i didn't know / forgot i need it. **thanks!** 
i used inmobi for admob. i'll test and come back with results!

**Comment by warcry2000** [comment]
@frozenxis For adcolony create this plugin, but inmobi do not know if there is a plugin out there. If you find it or have it, point it out here.
https://github.com/warcry2000/cordova-plugin-admob-mediation-adcolony

Here are some more, but they do not have it for video.
https://github.com/ratson/cordova-plugin-admob-free/issues/7

regards

**Comment by frozenxis** [comment]
thanks. i couldn't make rewards videos with inmobi :( 
released the app without them for now.. maybe in update
thanks for tip about adcolony

**Comment by detalpha** [comment]
Hi,
as related issues, when I use AdMob.prepareRewardVideo(),  I get Uncaught TypeError: AdMob.prepareRewardVideo is not a function warning. I had adcolony account and use your [cordova-plugin-admob-mediation-adcolony](https://github.com/warcry2000/cordova-plugin-admob-mediation-adcolony). is there additional code need to called before calling AdMob.prepareRewardVideo()? thank you

**Comment by warcry2000** [comment]
Hello @detalpha, 
Rewardevideo is still on test, if you want to test the code it is on a branch:
https://github.com/ratson/cordova-plugin-admob-free/pull/40
They are doing the last tests to release it.

Try this code and comment.

Regards

**Comment by ratson** [comment]
v0.6 is released
