### ISSUE TITLE
(Question) Keeping up to date with AdMob SDK

### ISSUE THREAD

**Issue by russellchapin** [ratson/cordova-plugin-admob-free#4]
Just came across this plugin yesterday (thanks for forking a free version, btw) and received this message in XCode: <code>You are currently using version 7.7.0 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes.</code> 

Wondering if you're planning on making stable updates as the SDK changes, thanks again.

**Comment by ratson** [comment]
I sent [a pull request](https://github.com/sunnycupertino/cordova-admob-sdklibs/pull/2) to the upstream before and got rejected.

So I will need to fork it to include updates, I should have some time this weekend to do it.

**Comment by russellchapin** [comment]
Awesome. Thanks.

**Comment by ratson** [comment]
Done
