### ISSUE TITLE
Stop show all banners in 13/11/2019

### ISSUE THREAD

**Issue by eomonteiro** [ratson/cordova-plugin-admob-free#403]
All banners stopped working on 13/11/2019, it is not new installation, the plugin is in applications already published, does anyone know why?

**Comment by tuannlm** [comment]
Same issue, using same code for all projects and now seems like some working and some not. With testing now it does not show anything even I had tested working few days ago

**Comment by eomonteiro** [comment]
Google will only display banners if it is published in the Play Store
