### ISSUE TITLE
Autoshow discrepancy between iOS and Android

### ISSUE THREAD

**Issue by becvert** [ratson/cordova-plugin-admob-free#41]
to workaround that issue I need to
```
AdMob.setOptions({
    autoShow : false,
    autoShowInterstitial : false
});
```

**Comment by ratson** [comment]
Please checkout v0.6, which can set `autoShow` per ad type

**Comment by becvert** [comment]
I checked it out.
Still need` autoShow : false` for iOS to work and `autoShowInterstitial : false` for Android

**Comment by ratson** [comment]
Could you try `admob.interstitial.config({autoShow: false})`?

**Comment by becvert** [comment]
argh yes, sorry I've still been using the old setConfig. I'll try again and tell you. thanks

**Comment by becvert** [comment]
it's working fine with v0.6.
my apologies.
and thank you for the great work!
