### ISSUE TITLE
Calling prepareInterstitial within the showInterstitial?

### ISSUE THREAD

**Issue by Script47** [ratson/cordova-plugin-admob-free#44]
I want to show consecutive ads without a too much of a delay in between, could I do the following,

```javascript
AdMob.prepareInterstitial({}, function () {
    AdMob.showInterstitial(function () {
        AdMob.prepareInterstitial();
   });
});
```
So the next time I call `showInterstitial` would it already be prepared?

**Comment by ratson** [comment]
Please checkout v0.6
