### ISSUE TITLE
npa: '1'  is an option ?

### ISSUE THREAD

**Issue by brunoalex** [ratson/cordova-plugin-admob-free#447]
admob.banner.show({id: {android: 'ca-app-pub-9718633180389415/5096728138', npa: '1' },}) 
but not sure if its displaying nonpersonalized ads.. i think its not... is there any way to do this ? tks

**Comment by alexp25** [comment]
As I found in the docs, it should be this way: ```admob.banner.config({id: 'ca-app-pub-9718633180389415/5096728138', adExtras: { npa: 1 }})``` then ```admob.banner.show()```. I'm not sure if there is a way to check if it's actually requesting non-personalized ads.

**Comment by brunoalex** [comment]
admob.interstitial.config({
 id: 'ca-app-pub-xx',isTesting: false,adExtras: { npa: 1 }
})   or      admob.interstitial.config({
 id: 'ca-app-pub-xxx',isTesting: false
}). 
is sending the same ads .. dont think it works

**Comment by brunoalex** [comment]
i think it works marking as closed
