### ISSUE TITLE
Testing Reward Videos / Events

### ISSUE THREAD

**Issue by rebrandsoftware** [ratson/cordova-plugin-admob-free#46]
I'm trying to get reward videos to show using the new API.  I have integrated AdColony mediation in AdMob, making a video-only ad unit.  I have also added cordova-plugin-admob-mediation-adcolony to my project.  AdMob lists the AdColony id as pending; I'm not sure if that affects testing or not.

I'm trying to use the new API like this:

```
showRewardVideo: function(autoShow) {
  
		admob.rewardvideo.config({
		    id: AdsAll.adObj.video,  //This is the video-only ad unit id from AdMob
		    isTesting: AdsAll.bTesting, //currently true
		    autoShow: autoShow //Passed into this function, currently true
		 });
    	
    	admob.rewardvideo.prepare();
    	admob.rewardvideo.show();
    	
    }
```

That code does display an interstitial test ad, but not a video.  Is there a video test ad available?

Additionally, I can't find which events are triggered after the reward video completes or is closed.  I don't see events for this in the new API docs.  I have tried logging to the console after all these possible events (gathered from old code or code in comments here) but nothing is showing up after calling rewardvideo.show():

```
admob.banner.events.LOAD_FAIL
admob.interstitial.events.LOAD_FAIL
admob.interstitial.events.LOAD
admob.interstitial.events.CLOSE
onFailedToReceiveAd
onReceiveRewardVideoAd
onPresentRewardVideoAd
onPresentStartedRewardVideoAd
onDismissRewardVideoAd
onRewardedVideo
```

My goal is to get events working in a test environment so that I can ensure the users will be properly rewarded after watching the video.

Thanks for this excellent plugin!

**Comment by ratson** [comment]
I have added list of events [here](https://ratson.github.io/cordova-plugin-admob-free/variable/index.html#static-variable-rewardvideo)

**Comment by rebrandsoftware** [comment]
Thanks!  Is there a test video from AdMob I should expect to see, or does it just show an interstitial image?

**Comment by rebrandsoftware** [comment]
Also, I was looking at [cordova-admob-mediation](https://github.com/rehy/cordova-admob-mediation ) because you link it in the docs.  I see it supports InMobi but I was unable to get it installed properly and can't find the JAR files for the SDK in the source.  

Since that didn't work I created an mediation plugin for InMobi here: [cordova-plugin-admob-mediation-inmobi](https://github.com/rebrandsoftware/cordova-plugin-admob-mediation-inmobi) that I think should work, and installs properly, but since this is the first time I've created one I wouldn't be surprised if it needs some minor modifications.  I'm still waiting on InMobi to send me a secret key before I can test it with admob-free.

**Comment by rebrandsoftware** [comment]
I have everything working now.  The problem I was having is that the ads were trying to load before I assigned the proper ad ID, causing it to load a default "interstitial test ad" instead of a video.

Now that I have the proper ad ids in place it's working as expected.

**Comment by technotip** [comment]
@rebrandsoftware Could you please share the code with us?

I'm using the same code you had posted earlier. In my case am not getting any kind of ad.
