### ISSUE TITLE
change js-module clobbers

### ISSUE THREAD

**Issue by becvert** [ratson/cordova-plugin-admob-free#48]
instead of window.admob, I suggest using cordova.plugins.admob

`<clobbers target="cordova.plugins.admob" />`

I feel like not enough plugins use cordova.plugins as a placeholder. it's a shame.

what do you think?

**Comment by ratson** [comment]
I am not sure if there is any advantage for using `cordova.plugins.admob`, and it seems too long for typing.
Could you point me to any reference that is recommending it?

**Comment by becvert** [comment]
I don't think there's actually any recommandation from cordova. I've just seen that in a few plugins.
But it's a smart move as one best practice in JavaScript is to avoid cluttering the global namespace.
I don't know if that's a big advantage but then I know where the cordova plugins are, and in DevTools I can use method autocompletion for instance.
And it isn't too long and I always create a var in that case, eg. `var admob = cordova.plugins.admob;` if I need to.
I put my own plugins under this placeholder, it's a personal preference in the end.
That's was just a suggestion. Feel free to close or wait for input from other devs.
Thanks

**Comment by vintage** [comment]
I'm good with the global `admob` variable (even if using it once and exposing it using angular2 service). I see no gain in changing this.
