### ISSUE TITLE
Failed to Load Ad

### ISSUE THREAD

**Issue by swaraasolutions** [ratson/cordova-plugin-admob-free#49]
Hi,
I just upgraded the version of plugin with the new api.

However, it is not showing ads any more just showing up an error 0 and reason Internal error.

I have verified my code 3 times here is the snippet
`
admob.banner.config({
          id: admobid.banner,
          isTesting: true,
          autoShow: true,
          size:admob.AD_SIZE.SMART_BANNER,
        });
        admob.banner.prepare();
`
@ratson any help appreciated

**Comment by Script47** [comment]
Is the trailing `,`  meant to be there after the `size` option?

**Comment by swaraasolutions** [comment]
Hi @Script47 i have removed the trailing slash. Seems this is an issue with Lenovo K4 Note Phones. not sure what's wrong really, all other devices are working fine.
