### ISSUE TITLE
Project won't build with update.

### ISSUE THREAD

**Issue by russellchapin** [ratson/cordova-plugin-admob-free#5]
<h1>FIXED</h1>
After manually copying the Header folder to the GoogleMobileAds.framework root, the SDK files are found, but now the build fails with error instead: 
<code>no visible @interface for 'CDVAdMob' declares the selector 'md5:'</code>

I'll revert to previous version in the meantime.

**Comment by russellchapin** [comment]
Ah, wasn't setting the flag, it's working now. Thanks!

**Comment by russellchapin** [comment]
Tested on another computer. Same error.

**Comment by russellchapin** [comment]
Was just going to post that I fixed it by adding the library search path in XCode, but it's now working on its own with the update. Thanks.

**Comment by ratson** [comment]
Is that your problem fixed with the latest update? Or anything I could help?

**Comment by russellchapin** [comment]
Yep, the SDK search paths weren't being linked. Figured it out like 10 minutes before you pushed up 0.1.3, which fixed it haha. Thanks!

**Comment by ratson** [comment]
Close as problem resolved.
