### ISSUE TITLE
i can not show interstitial ad.

### ISSUE THREAD

**Issue by shkim6827** [ratson/cordova-plugin-admob-free#50]
Hello, I have some problem.
First, my HTML tag is ...
**<script>
    document.addEventListener('deviceready', function() {

      admob.rewardvideo.config({
       id: admobid.reward,
       isTesting: true,
       autoShow: false,
      })

      admob.rewardvideo.prepare()

      admob.interstitial.config({
        id: admobid.interstitial,
        isTesting: true,
        autoShow: true,
      })

      admob.interstitial.prepare()

      document.getElementById('showAd').onclick = function() {
        admob.rewardvideo.show()

      }

    }, false)
</script>**

When I use that code, I can not see my reward ad when i click html tag(id = "showAd")
 What can I do?
Sorry for my English skill, and thanks for plugin!

**Comment by vintage** [comment]
@shkim6827 I'm not sure what are you talking about - reward video or interstitials? In the title you mention interstitial ad, but the code is about displaying reward video. Could you be more precise?

**Comment by ratson** [comment]
Close as no reply.
