### ISSUE TITLE
Interstitial Ad not showing

### ISSUE THREAD

**Issue by Script47** [ratson/cordova-plugin-admob-free#52]
Since the update, my ads won't show for some reason, my code is as shown below.

```javascript
 admob.interstitial.config({
        id: 'my-id',
        isTesting: false
 });

admob.interstitial.prepare();

admob.interstitial.show();
```

Any ideas?

**Comment by ratson** [comment]
Are you calling `admob.interstitial.show()` immediately? Please have a look on [the example](https://github.com/ratson/cordova-plugin-admob-free/blob/master/examples/basic/www/js/index.js),
see if you code has any difference.

**Comment by Script47** [comment]
@ratson Is there an event for me to use to check if the ad is ready?

In my code, I'm not immediately calling it, it only runs if a condition is met which happens later on in the app.

**Comment by vintage** [comment]
@Script47 In current version you could simply use:

```
admob.interstitial.prepare();
document.addEventListener('admob.interstitial.events.LOAD', function(event) {
  admob.interstitial.show();
})
```

In the next release you will be able to prepare the interstitial and checks if it's ready on-demand using `admob.interstitial.isReady().then(isReady => console.log("Am I ready?", isReady))`.

Also check the docs https://ratson.github.io/cordova-plugin-admob-free/variable/index.html#static-variable-interstitial and examples pointed out by ratson.

**Comment by Script47** [comment]
Odd... I have all the events, but no errors are showing at all, neither is the ad.

**Comment by Script47** [comment]
@ratson @vintage 

**Bump** - Still not working, any ideas?

**Comment by vintage** [comment]
@Script47 

Does this one works for you?
```
admob.interstitial.config({
        id: <PUT_YOUR_ID>,
        isTesting: true,
        autoShow: true
      });
admob.prepare();
```

If not, what errors shows on the browser console or xcode/adb console?

**Comment by Script47** [comment]
**Update**

For those of you who (like me) were struglling to get this to work using Intel XDK should note that you use use `deviceready` instead of the `app.Ready` function, this was causing the plugin not to work for me.
