### ISSUE TITLE
Prepare in background rather than on UI thread

### ISSUE THREAD

**Issue by becvert** [ratson/cordova-plugin-admob-free#53]
Hello,

I'm no Thread master, but I see unwelcomed short freezes on my UI when I prepare my ads in advance of their showing.

So shouldn't the `prepare` calls be running in a background thread instead of on the UI thread?

for instance [InterstitialExecutor.java#L37](https://github.com/ratson/cordova-plugin-admob-free/blob/master/src/android/interstitial/InterstitialExecutor.java#L37)

`cordova.getActivity().runOnUiThread`

should be

`cordova.getThreadPool().execute`?

**Comment by ratson** [comment]
The implementation is inherited from the original fork, feel free to change that and test if it works.
PR is always welcome.

**Comment by becvert** [comment]
No worries. I know it's inherited. I'll do some tests and make a PR if it works indeed

**Comment by becvert** [comment]
AdMob requests that it runs on UI thread. Nothing we can do about that.
