### ISSUE TITLE
Ionic 2

### ISSUE THREAD

**Issue by bflopez** [ratson/cordova-plugin-admob-free#55]
I am looking to use this app in my Ionic 2 projects. It seems there is an issue importing the plugins directly with TypeScript so I used this method:

```(<any>window).plugins.AdMob.createBannerView();```

I saw you had updated the plugin to have Classes banner:Banner. I tried to use it but I couldn't get it to work.

The problem I have with this is that Ionic 2 comes with a native "AdMob" plugin from https://github.com/floatinghotpot/cordova-admob-pro that uses the same name"AdMob"

Since I am not importing the native plugin in my TypeScript file I feel as if it shouldn't be accessing that plugin API. How can I be sure I am using this plugin and not the native one?

**Comment by bflopez** [comment]
I removed this plugin and it didn't work. Added it back and it worked again. Seems I am accessing this plugin. I still would like some info on how to not use the deprecated functions in Ionic 2 if possible. Thank you.

**Comment by bflopez** [comment]
(<any>window).plugins.AdMob.banner.config( {})
(<any>window).plugins.AdMob.banner.prepare();
(<any>window).plugins.AdMob.banner.show();

I don't know why I didn't think this would work. Closing but if anyone else runs into this issue I hope this helps them spend less time than me figuring it out.

**Comment by vintage** [comment]
@bflopez I'm also using the Ionic 2 for my projects, and I've even wrote a simple injectable provider to make things easier (to for example switch between different plugins without touching the pages/components). I'm still adding there new stuff, as I find anything is needed in one of my projects.

```
import { Injectable } from "@angular/core";

@Injectable()
export class AdService {
  constructor() {}

  initialize(banner: string, interstitial: string, reward: string) {
    let engine = this.getEngine();
    if (engine) {
      engine.banner.config({
        id: banner,
        isTesting: false,
        autoShow: true,
        overlap: false
      });

      engine.interstitial.config({
        id: interstitial,
        isTesting: false,
        autoShow: false
      });

      engine.rewardvideo.config({
        id: reward,
        isTesting: false,
        autoShow: false
      });
    }
  }

  getEngine() {
    let engine = window["admob"];
    return engine;
  }

  showBanner() {
    let engine = this.getEngine();
    if (!engine) {
      return;
    }
    
    engine.banner.prepare();
  }

  removeBanner() {
    let engine = this.getEngine();
    if (!engine) {
      return;
    }

    engine.banner.remove();
  }

  prepareFullScreen() {
    let engine = this.getEngine();
    if (!engine) {
      return;
    }

    engine.interstitial.prepare();
  }

  showFullScreen() {
    let engine = this.getEngine();
    if (!engine) {
      return;
    }

    engine.interstitial.show();
  }

  isFullscreenReady() {
    return new Promise(resolve => {
      let engine = this.getEngine();
      if (!engine) {
        resolve(false);
      } else {
        engine.interstitial.isReady().then(isReady => {
          resolve(isReady);
        });
      }
    });
  }

  prepareRewardVideo() {
    let engine = this.getEngine();
    if (!engine) {
      return;
    }

    engine.rewardvideo.prepare();
  }

  showRewardVideo() {
    let engine = this.getEngine();
    if (!engine) {
      return;
    }

    engine.rewardvideo.show();
  }

  isRewardVideoReady() {
    return new Promise(resolve => {
      let engine = this.getEngine();
      if (!engine) {
        resolve(false);
      } else {
        engine.rewardvideo.isReady().then(isReady => {
          resolve(isReady);
        });
      }
    });
  }
}
```

Using it is not any kind of magic, so probably anyone playing around with Angular 2 knows how to inject it into the project.

**Comment by ratson** [comment]
Re-open this to keep track for future improvement.
It should be something like https://github.com/driftyco/ionic-native/blob/master/src/plugins/admob.ts

**Comment by calebeaires** [comment]
Hi everyone.

I arrived to this project when finding some way to make sure interstitial is fully loaded before calling its show function. **I have received letter from Google that complains about that**. My [problem was reported here](https://github.com/floatinghotpot/cordova-admob-pro/issues/534). 

The example above seems to have this check feature (`  isFullscreenReady() `). May you help me with this issue? Is the example above a good start to it!

**Comment by vintage** [comment]
@ratson I use Ionic on the daily basis and just found out they have introduced support for this library. Awesome! Don't know yet how does it work and if it exposes all the supported interfaces, but definitely worth to look at. I won't be using it in my current projects, but will give it a try in the project I'm currently working at.

http://ionicframework.com/docs/v2/native/adbmobfree/
https://github.com/driftyco/ionic-native/tree/master/src/%40ionic-native/plugins/admob-free

**Comment by ratson** [comment]
@vintage Thanks for the information, good to know it is supported.
