### ISSUE TITLE
I can't seem to get any ad to work.

### ISSUE THREAD

**Issue by jhonoi** [ratson/cordova-plugin-admob-free#56]
I've tried for quite some time now but i cant seem to get any ad to work. Can I get some help please?
This is my code.

<!DOCTYPE html>
<html>
<head>
    <title>banner demo</title>
    <style>
        .bodyStyle{
            font-size: 32px;
        }
    </style>
</head>
<body >
<button id="showAd">Show</button>
<script type="text/javascript">

	var admobid = {}
if (/(android)/i.test(navigator.userAgent)) {  // for android & amazon-fireos
  admobid = {
    banner: 'ca-app-pub-id',
    interstitial: ' ca-app-pub-id',
  }
} else if (/(ipod|iphone|ipad)/i.test(navigator.userAgent)) {  // for ios
  admobid = {
    banner: 'ca-app-pub-3940256099942544/2934735716',
    interstitial: 'ca-app-pub-3940256099942544/4411468910',
  }
}

document.addEventListener('deviceready', function() {
  admob.banner.config({
    id: admobid.banner,
    isTesting: true,
    autoShow: true,
  })
  admob.banner.prepare()

  admob.interstitial.config({
    id: admobid.interstitial,
    isTesting: true,
    autoShow: false,
  })
  admob.interstitial.prepare()

  document.getElementById('showAd').disabled = true
  document.getElementById('showAd').onclick = function() {
    admob.interstitial.show()
  }

}, false)

document.addEventListener('admob.banner.events.LOAD_FAIL', function(event) {
  console.log(event)
})

document.addEventListener('admob.interstitial.events.LOAD_FAIL', function(event) {
  console.log(event)
})

document.addEventListener('admob.interstitial.events.LOAD', function(event) {
  console.log(event)
  document.getElementById('showAd').disabled = false
})

document.addEventListener('admob.interstitial.events.CLOSE', function(event) {
  console.log(event)

  admob.interstitial.prepare()
})

</script>
</body>
</html>

**Comment by vintage** [comment]
What kind of errors do you have?

**Comment by ratson** [comment]
Close as no reply.
