### ISSUE TITLE
Does the plugin support native ads?

### ISSUE THREAD

**Issue by shastox** [ratson/cordova-plugin-admob-free#57]
I did not find any plugins that support native ads. Thanks.

**Comment by ratson** [comment]
Refer to https://github.com/floatinghotpot/cordova-admob-pro/issues/391#issuecomment-221457376, it seems not possible.
Maybe you could help if you know how to do it.

**Comment by ratson** [comment]
Close as if it is impossible.

**Comment by chinlun** [comment]
@ratson Links to those URL are no longer available. Can you share why NativeAd is not possible?

**Comment by appsOne** [comment]
@ratson  I thinks that is possible. Can you use same technique like facebook ads plugin for display native ads?
