### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by m6246** [ratson/cordova-plugin-admob-free#59]
How would one provide config.location? I'm not sure about iOS but for Android this is a native object (https://developer.android.com/reference/android/location/Location.html)

**Comment by ratson** [comment]
@m6246 How this is related to AdMob?

**Comment by m6246** [comment]
Hi Ratson, is is used for targeting purposes.

https://github.com/ratson/cordova-plugin-admob-free/blob/d44d91e8a053f09a8af477d6b5ec23308c5530bf/src/android/AdMob.java#L188

**Comment by m6246** [comment]
Actually.. I just found about this, doh

https://github.com/ratson/cordova-plugin-admob-free/blob/d44d91e8a053f09a8af477d6b5ec23308c5530bf/src/android/AdMobConfig.java#L123

So this basically answers my question. Still worth adding to the docs though ;)

**Comment by ratson** [comment]
Documentation added, see https://ratson.github.io/cordova-plugin-admob-free/typedef/index.html#static-typedef-BaseConfig
