### ISSUE TITLE
Plugin Doesn't Work With Windows 10

### ISSUE THREAD

**Issue by RobPosener** [ratson/cordova-plugin-admob-free#6]
The plugin seems to work with Android OK but I am unable to get it to work with Windows 10.
All of the code seems to say "Windows Phone" and "Windows 8" and "Windows 8.1" but what about "Windows 10" and "Universal Application Platform (UAP)/Universal Windows Platform (UWP)"?
No error is thrown... just nothing is displayed.

**Comment by ratson** [comment]
@RobPosener  I am not sure if Cordova plugin could work for Windows 10. Do you have any example plugin on how it is working?

I will probably could support Windows 10 well, as I don't use it. If anyone could help, PR is welcome.

**Comment by vintage** [comment]
@RobPosener: AdMob doesn't support Windows 10 nor Windows Mobile platform, so it's waste of energy to make the plugin compile for these devices.

The only working ads platform which I'm aware of is the Pubcenter (Microsoft product). I've been using it for some time in my native app, but don't have any experience in integrating it with the cordova. Let me know in case you get any details about the integration, as it would be really cool to to have an option to display ads in the cordova based Windows apps/games.

http://stackoverflow.com/questions/31810331/google-admob-and-windows-10-universal-apps

**Comment by RobPosener** [comment]
Gerday Kamil,
Thanks for you comments and insight.
They confirm my investigations.
If I find anything or come up with a workable solution, I'll let you know.
It won't be in the next 12-18 months... I'm about to drive all the way
around Australia.

Rob

Regards
*Rob Posener*
0419 012 627

**Comment by vintage** [comment]
@ratson We can close the issue now, as we can't do anything to make it work on the Windows 10.
