### ISSUE TITLE
Block click on banner

### ISSUE THREAD

**Issue by danaraujjo** [ratson/cordova-plugin-admob-free#64]
Good evening! Is there a way to block the click? I'm creating an app for kids ... and I would like the banner to only print.

Thanks!

**Comment by geekyguy18** [comment]
NO! don't ever block clicks, **this will violate AdMob terms** and your APP will be banned from play store and your AdMob account will be banned too. Another thing, if you block clicks how you will generate revenve?

**Comment by ratson** [comment]
@danaraujjo Would you elaborate more about why do you want to do that?

**Comment by danaraujjo** [comment]
"Porque você é criança menor de 4 anos... é pra criança não ficar clicando e saindo do app, eu queria bloquear isso. Ganharia apenas com impressões e não com cliques."

Because you are a child under 4 years ... it is for the child not to be clicking and leaving the app, I wanted to block it. It would only win with impressions and not with clicks.

**Comment by ratson** [comment]
@danaraujjo As @geekyguy18 has pointed out, it is not a good way to avoid children clicking the ads. You could choose to not show the ads for children.
