### ISSUE TITLE
How to know if user watch the entire reward video

### ISSUE THREAD

**Issue by calebeaires** [ratson/cordova-plugin-admob-free#67]
There is an method to get reward ad when it is read, but how to know if the user watch entire reward video or don`t? Right know I am calling this

```
    showRewardVideo() {
        let engine = this.getEngine();
        if (!engine) {
            return;
        }
        this.isRewardVideoReady().then((isReady) => {
            console.log(isReady);
            if (isReady) {
                engine.rewardvideo.show().then((res) => {
                    console.log(res);
                }).catch((err) => {
                    console.log('erro', err);
                });
            } else {
                this.prepareRewardVideo();
            }
        });
    }
```

**Comment by vintage** [comment]
Your current code makes a `console.log` just after the reward video has been shown. If you want to do some extra action when full video has been watched you need to use event:

```
    document.addEventListener('admob.rewardvideo.events.REWARD', () => {
      console.log("GIVE USER A REWARD HERE");
    });
```

**Comment by PrithiviRajG** [comment]
@calebeaires I am not able to get reward videos in my App. can you please share the file where you have configured coded reward video.

Thanks in advance!

**Comment by calebeaires** [comment]
@PrithiviRajG Are you using an emulator or an real device to test it? With this plugin rewards video does not works on a real device.

**Comment by PrithiviRajG** [comment]
@calebeaires I am using real device. How to use it or test it for real device?
any other ways to use reward videos in cordova App using AdMob?

**Comment by calebeaires** [comment]
@PrithiviRajG with Android Studio, download and active emulated devices, then you can emulate your cordova app on it with something like this: ```cordova emulate android```. [video tips](https://www.youtube.com/watch?v=ywynAxPjU9w)

**Comment by merbin2012** [comment]
This will produce Uncaught SyntaxError: Unexpected token )

**Comment by vintage** [comment]
Closing it, as answer has been already provided in the first comment. That's how you recognize if the reward video has been fully watched.
