### ISSUE TITLE
Checking if banner has been prepared

### ISSUE THREAD

**Issue by Script47** [ratson/cordova-plugin-admob-free#68]
I have an app, when the user changes to a different page, do I need to re-prepare the banner or can I just show it?

**Comment by calebeaires** [comment]
Better re-prepare!

**Comment by vintage** [comment]
@Script47 I'm always preparing & showing the banner at the first screen the user visits. After that I don't have to do anything with the banner itself as during navigation it persist in his location. I've never had to re-prepare the ad banner as I'm not aware of any scenario which would require it (maybe hidding the banner for some reason and then showing it again?).
