### ISSUE TITLE
Mediation networks

### ISSUE THREAD

**Issue by becvert** [ratson/cordova-plugin-admob-free#7]
Hello, 
At last a no ad sharing admob plugin. great job!
Does it support mediation for iAd, FacebookAds for instance?
How difficult would it be to implement that?
I'm willing to have a look into it but need some hints.
Thank you

**Comment by ratson** [comment]
Currently, there is no mediation support as I don't use any at the moment.
I am not sure the complexity for adding it, but you can have a look on https://github.com/floatinghotpot/cordova-admob-pro for reference.

I am happy to review / merge any pull request to add this feature.

**Comment by becvert** [comment]
actually, at a quick glance, it seems pretty straight forward.
it would take the form of plugins, for instance:
cordova-plugin-admob-free-facebookads
cordova-plugin-admob-free-iad
I'll see what I can do.

**Comment by becvert** [comment]
I added 2 mediation plugins:

[cordova-plugin-admob-mediation-facebook](https://github.com/becvert/cordova-plugin-admob-mediation-facebook)

[cordova-plugin-admob-mediation-adbuddiz](https://github.com/becvert/cordova-plugin-admob-mediation-adbuddiz)

iAd has been discontinued of course.

**Comment by ratson** [comment]
@becvert Good work! I've made you a collaborator on the project so you can update the documentation about how to integrate mediation.

**Comment by vintage** [comment]
@becvert: Are you using these mediation plugins in any of your mobile apps? To be honest I'm looking for some admob library for cordova which will have working mediations - neither floatinghotpot or cranberrygame have working system, as they have a bunch of open issues which are not addressed and it's impossible to build app using eg. inmobi/adcolony.

Can you also point me and other devs which will look into this issue how have you started with writing plugins for it? Just some initial resources/hints, we're technical guys we know how to continue the stuff.

Other than that I'm going to migrate to this library today as it looks promising, we will see what the future will bring :)

**Comment by becvert** [comment]
@vintage Yes I'm using these mediation plugins in my apps. 
I'm generating impressions and revenue.
Only using interstitials though. Haven't tested banners.
I'm going to publish them to npm soon.

All a plugin does is adding the adapters ( .jar and .framework) into the project.

You'll find a bunch of network adapters on [this page](https://firebase.google.com/docs/admob/android/mediation-networks). 
You may want to check directly with a given network if they provide more resources and guidance..

for instance with [Adbuddiz](https://github.com/becvert/cordova-plugin-admob-mediation-adbuddiz) there is some manual config for iOS to do in addition. I coudn't get the plugin to do it.

Getting the rewarded video ads to work with mediation might be a more complex work.
Do not know if that's even possible.
