### ISSUE TITLE
admob plugin cihaz hatası

### ISSUE THREAD

**Issue by omerorkmez** [ratson/cordova-plugin-admob-free#70]
Hi,

I can make a good compilation before adding Admob plugin. After adding, I get the following error.
I would like your support.

![image](https://cloud.githubusercontent.com/assets/28788028/26214769/483085d6-3c06-11e7-8d94-a916079e77e8.png)

**Comment by centrual** [comment]
com.google.android.gmsplay-services-ads+ bulunamadı diyor.

Sdk Manager programını açıp, (en altta tools kısmında olmalı) google play services sdk'sını kurman gerekiyor.

**Comment by omerorkmez** [comment]
Merhaba,

Dediğinizi kurdum ancak aynı sorun devam ediyor. SDK manager'da eksik olan başka şeyler vardı onları da kurup tekrar deneyeceğim.

Resimde en altta bulunan şu hali ile ilgili bir sorun olabilir mi?
Hata		Picked up _JAVA_OPTIONS: -Xmx512M


![image](https://cloud.githubusercontent.com/assets/28788028/26216150/b6c5f652-3c0b-11e7-860a-210591744dbd.png)

**Comment by omerorkmez** [comment]
Merhaba,
54 hata vardı, şimdi 14 hata kaldı. ancak bu alt taraftaki hata duruyor.

![image](https://cloud.githubusercontent.com/assets/28788028/26216729/d2e5acae-3c0d-11e7-802f-dba66fc07dcf.png)

![image](https://cloud.githubusercontent.com/assets/28788028/26216743/e07c5db8-3c0d-11e7-8dcf-4bfc6411eb37.png)

**Comment by centrual** [comment]
Merhaba @omerorkmez 

İlk sorununuz sdk ile ilgiliydi. Sizin hata dediğiniz kısım bir hata değil, derleme argümanlarıdır.

Şuanki hata ilk hatanızdan farklı. Şu anki hata ise `C:/Users/egzantirik7/Documents/Visual Studio 2017/Projects/test1/test1/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-base/10.2.6/res/drawable-hdpi-v4/common_google_singin_btn_icon_dark_normal_background.9.png` dosyasının dosya yolunun çok uzun olduğu için okunamadığı. 240 karakterin altında olması gerekmekte.

Proje klasörünüzü direk `C:/` içerisine alarak bu sorunu çözebilirsiniz.

**Comment by omerorkmez** [comment]
Desteğin için çok teşekkür ederim, dediğinizi aynen yaptım tüm hata ve uyarılar gitti. sorunsuz çalışıyor şuan. 
Şimdi sırada ilk reklam testi var :)

Bu arada web sayfanızı inceledim. çok güzel bir tasarım. Referanslar çok sağlam, tebrikler :)

İyi akşamlar.

**Comment by centrual** [comment]
Benim için zevkti @omerorkmez 

Güzel bir gün geçirmeni dilerim.

**Comment by ratson** [comment]
WOW, it is great to know this plugin has Turkish users.
Thanks for @centrual helping out.
@omerorkmez Is your problem solved?

**Comment by centrual** [comment]
Hello @ratson 

Thanks for open source admob plugin. You'r super hero! 😃
The problem solved. He said in Turkish already.

Have a great day!

**Comment by omerorkmez** [comment]
Hi @ratson

Your fame arrieved to Turkey
Problem is solved by @centrual.

Thanks for your interest.

Thanks & Have a great weekend.

**Comment by ratson** [comment]
Thank you for the kind words, I will close this.
