### ISSUE TITLE
Reaction Button

### ISSUE THREAD

**Issue by omerorkmez** [ratson/cordova-plugin-admob-free#72]
Hi,

I applied the example, but it does not react when I click on the button.

I added the code here at the end of the script.js page.
I may have been making simple mistakes because I just started.

Do not blame me for tiring you. :((

I will then make the award-winning ad insertion, which can be contacted by someone who can give you paid support.
omerorkmez@gmail.com
 
I would like your support.

**Comment by ratson** [comment]
@omerorkmez Thank you for interesting in paid support, I didn't expect that and have no idea how it should work. I will email you and see if anything I could help.

**Comment by omerorkmez** [comment]
Hi,

I am waiting for your mail.

Thank you
