### ISSUE TITLE
interstitial.isReady() always yields false even in testing mode

### ISSUE THREAD

**Issue by githistory** [ratson/cordova-plugin-admob-free#73]
What I wanna do: when there is no ad (for example, user has already watched max number of ads for a period in admob settings), go direct to my app logic, when there is ad, display interstitial and then go to my app logic.

Since there is no documentation, I'm writing following code via guessing:

```typescript
    this.adMobFree.interstitial.prepare()
      .then(()=>{
        return this.adMobFree.interstitial.isReady()
      })
      .then((ready)=>{
        console.log(ready)
        if (ready) {
          // do something
        } else {
          // do something else
        }
      })
```

Am I doing it wrong?

**Comment by ratson** [comment]
@githistory Calling `isReady()` immediately after `prepare()` will likely always be `false`, as AdMob typically require some time to fetch the ads before it is ready.
For your use case, you probably would listen to `admob.interstitial.events.LOAD` and keep track the state yourself.

Have a look on the example if you did not read it yet, https://github.com/ratson/cordova-plugin-admob-free/blob/master/examples/basic/www/js/index.js

**Comment by githistory** [comment]
@ratson, thanks for getting back!

Are you saying I can call isReady in LOAD handler? Will it reflect cases where there is no ad to display?

**Comment by ratson** [comment]
You should not need to check `isReady` when you have the LOAD event, as the event implied there is ad ready to serve. However, after you `show` the ad, you need to wait for the next LOAD event.
Is that answer your question?

**Comment by githistory** [comment]
So in the LOAD event, how do I tell if I should call show() or do my app logic stuff? That is, how do I tell if there indeed is an ad or not?

**Comment by ratson** [comment]
Did you try the example?

**Comment by ratson** [comment]
Close as no reply.
