### ISSUE TITLE
Config are not loaded in release

### ISSUE THREAD

**Issue by caciobanita** [ratson/cordova-plugin-admob-free#74]
if i running ionic cordova run android, are showing real adds,
but if i run ionic cordova run android --prepare - are showing only test ads
any suggestions?

**Comment by caciobanita** [comment]
https://github.com/ratson/cordova-plugin-admob-free/issues/83#issuecomment-313189358

**Comment by ratson** [comment]
Duplicate to https://github.com/ratson/cordova-plugin-admob-free/issues/83
