### ISSUE TITLE
Ionic: Fail to load resource

### ISSUE THREAD

**Issue by adappter** [ratson/cordova-plugin-admob-free#77]
Hey there,
I get this error:
Failed to load resource: The requested URL was not found on this server.
file:///var/containers/Bundle/Application/323813D6-3E08-42C1-95CD-F06A5F53F1F7/PoKo.app/www/plugins/cordova-plugin-admob-free/www/admob.js.map
 
But the plugin is correctly installed in the platform directory under ios.

**Comment by merbin2012** [comment]
Did you get the solution? please share

**Comment by darkthsideous** [comment]
@merbin2012 @adappter did you ever get this resolved for IOS. Please share
