### ISSUE TITLE
Different AdSizes do not work for banner ads

### ISSUE THREAD

**Issue by prantikv** [ratson/cordova-plugin-admob-free#84]
Love the plugin so far. But before I move over from AdMobPro I wanted to test the plugin thoroughly. Most of the times I use the "SMART_BANNER" banner ad. But during testing I fount that other ad sizes for banner do not work.

Here is my banner ad config:

```
    const bannerConfig: AdMobFreeBannerConfig = {
      // add your config here
      // for the sake of this example we will just use the test config
      id: 'ca-pub-xxxxxxxxxxx',
      isTesting: true,
      autoShow: false,
      // bannerAtTop: true,
      size:'WIDE_SKYSCRAPER'
    };
```

Note here that I have tested the app with a live ad id as well as the test id. None of which work.

Differnt ad sizes are taken form the plugin file [here](https://github.com/ratson/cordova-plugin-admob-free/blob/master/src/js/banner.js#L34)  as well as form what are mentioned in the docs [here](https://ratson.github.io/cordova-plugin-admob-free/typedef/index.html#static-typedef-BANNER_SIZE).

I have tested this on Android 5 emulator and Android 6 device.

Kindly let me know if I am missing something here.

**Comment by ratson** [comment]
The latest version should fix this.
