### ISSUE TITLE
admob.banner.events.OPEN

### ISSUE THREAD

**Issue by amokrunner** [ratson/cordova-plugin-admob-free#91]
The documentation includes this event: 

admob.banner.events.OPEN

but the event doesn't appear to trigger.

**Comment by sekocit** [comment]
Hi @amokrunner ,

You need to bind this event to a function. Like:

`document.addEventListener("admob.banner.events.OPEN", onBannerOPEN, false);
function onBannerOpen(){console.log("Banner Opened")};`

**Comment by lolaswift** [comment]
@sekocit .
the banner OPEN and CLOSE events are not working on IOS.
@amokrunner have you ever got it work?
