### ISSUE TITLE
Admob Always shows Test Ads !

### ISSUE THREAD

**Issue by hemant07rulz** [ratson/cordova-plugin-admob-free#92]
This is how I am calling it. 

>  showBanner() {
>         let bannerConfig: AdMobFreeBannerConfig = {           
>             autoShow: true,
>             id: 'ca-app-pub-xxxxxxxxxxx/xxxxxxx'
>         };
>         this.admob.banner.config(bannerConfig);
>         this.admob.banner.prepare().then(() => {
>             // success
>         }).catch(e => console.log(e));
>     }
> 
The app is live on Play store. Still it shows only test ads even after 1 day ! Please advice. Thank you

**Comment by anilk533** [comment]
Same problem here also
still not resolved plz let me know if u solved

**Comment by ratson** [comment]
Duplicate to https://github.com/ratson/cordova-plugin-admob-free/issues/69
