### ISSUE TITLE
Unable to show banner on apk release version

### ISSUE THREAD

**Issue by curtis18** [ratson/cordova-plugin-admob-free#99]
I find an app cannot show banner on apk release version, but it works fine on testing version in Android emulator. When I tried to build an app to production version and run the code on testing mode again. The following message will appear on debug console.

**"Native: tried calling AdMobFree.config, but the AdMobFree plugin is not installed.
Install the AdMobFree plugin: 'ionic cordova plugin add cordova-plugin-admob-free'"**

I have to run >npm install --save @ionic-native/admob-free in order to let the message above disappeared. Please help. Thank you.

**Comment by vietdh01** [comment]
Hi, is your issue resolved? I am having same problem, please help, thank you!

**Comment by vietdh01** [comment]
I am using Ionic 2 and my problem is solved, just add Admob library and function to app.component.ts not to home.ts.
Thank to this topic: https://forum.ionicframework.com/t/ionic-doesnt-work-with-admob/96985/3

**Comment by curtis18** [comment]
My problem is resolved. I just finally tried to reinstall all AdMobFree, Android Studio, NPM, Cordova, and Ionic. The function can work no matter it is located in home.ts / app.component.ts. It should work after updating all software's version. Hope it can help. Thank you.
